using System.Diagnostics;
using System.Numerics;
using System.Text;
using System.Text.Json;
using Ncma.Animation;
using Ncma.Editor.Protocol;
using Ncma.Editor.Services;
using Ncma.Gui;
using Ncma.Interop;
using Ncma.Platform;
using Ncma.Rendering;
using Ncma.Ui;

internal static unsafe class MontageSequenceTests
{
    private static void Check(bool v,string reason=""){if(!v)throw new Exception("M6.8-C2 actual sequence: "+reason);}
    private static void Reject(Action a){try{a();}catch(Exception e)when(e is ArgumentException or InvalidOperationException or JsonException){return;}throw new Exception("Invalid isolated sequence accepted.");}
    private static void Click(GraphInspectionTests.Fixture f,ulong high,ulong low,double value=0){f.Click(high,low,value);f.Build();}
    private static void Text(GraphInspectionTests.Fixture f,ulong high,ulong low,string text){byte[] bytes=Encoding.UTF8.GetBytes(text);var e=f.Event(high,low);e.TextLength=(uint)bytes.Length;f.View.Apply([e],bytes);f.Build();}
    private static AnimationMontageDefinition Save(GraphInspectionTests.Fixture f)
    {
        var w=f.Writer!;var d=w.Capture()!;Guid slot=Guid.NewGuid(),attack=Guid.NewGuid(),recovery=Guid.NewGuid();var m=new AnimationMontageDefinition(1,Guid.NewGuid(),"Isolated action",f.Rig,[new(slot,"Body",attack,10,true,true,0,.2)],[new(attack,"Attack",slot,f.Clip,.1,.4,recovery),new(recovery,"Recovery",slot,f.Clip,.4,.8,Guid.Empty)]);
        var output=d.Nodes.Single(n=>n.Kind==AnimationNodeKind.Output);var edge=d.Links.Single(l=>l.To==output.Id);var node=AnimationGraphNode.Create(Guid.NewGuid(),"Body",AnimationNodeKind.Slot) with{SlotId=slot};
        w.ApproveFileWrite(w.Stamp,w.Path!,f.Graph,true);w.Begin(w.Stamp);w.ApplyDraft(AnimationGraphEdits.Operations(new{op="montage.upsert",montage=m},new{op="node.upsert",node},new{op="link.delete",id=edge.Id},new{op="link.upsert",link=new AnimationGraphLink(Guid.NewGuid(),edge.From,"pose",node.Id,"pose")},new{op="link.upsert",link=new AnimationGraphLink(Guid.NewGuid(),node.Id,"pose",output.Id,"pose")},new{op="event.upsert",marker=new AnimationEventMarker(Guid.NewGuid(),f.Clip,.15,"Attack data")},new{op="event.upsert",marker=new AnimationEventMarker(Guid.NewGuid(),f.Clip,.45,"Recovery data")}));Guid id=w.PrepareLocal();var review=w.CaptureReview(id);w.Approve(review,review.Fingerprint,review.Graph,true);w.CommitLocal(id);f.View.SynchronizeGraph();f.Build();return m;
    }
    private static AnimationSequenceCase Case(AnimationMontageDefinition m,int steps=8)
    {
        Guid slot=m.Slots[0].Id,recovery=m.Sections.Single(s=>s.Name=="Recovery").Id;return new(.1,steps,[],[new(1,AnimationSequenceAssertionKind.SlotActive,slot,1),new(2,AnimationSequenceAssertionKind.MontageOutcome,slot,3),new(3,AnimationSequenceAssertionKind.SlotSection,recovery,0),new(4,AnimationSequenceAssertionKind.SlotWeight,slot,.5),new(8,AnimationSequenceAssertionKind.SlotActive,slot,0)]){MontageRequests=[new(1,slot,MontageRequestKind.Play,Guid.Empty,10),new(2,slot,MontageRequestKind.Play,Guid.Empty,9),new(3,slot,MontageRequestKind.Jump,recovery,10),new(4,slot,MontageRequestKind.Cancel,Guid.Empty,10),new(5,slot,MontageRequestKind.Play,Guid.Empty,20),new(6,slot,MontageRequestKind.Play,Guid.Empty,20),new(7,slot,MontageRequestKind.Cancel,Guid.Empty,20),new(7,slot,MontageRequestKind.Jump,recovery,20)]};
    }
    internal static IEnumerable<(string,Action)> Cases(string output,string repository,string plugins)
    {
        yield return("M6.8-C2 actual NCA isolated controls/Notify/root/terminal/copied input/no World/history",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);var m=Save(f);var s=f.Writer!.Sequences;s.PrepareTrusted();byte[] scene=f.Owner.Document.CaptureBytes(),file=File.ReadAllBytes(f.File);var state=f.Owner.Edit!.State;Guid id=s.ProposeLocal(Case(m));var copy=s.CaseCopy(id);copy.MontageRequests[0]=copy.MontageRequests[0] with{Priority=0};var r=s.RunLocal(id);Check(r.Passed&&r.RootMotionSupported&&r.Timeline.All(t=>t.Root is not null)&&r.Timeline.Sum(t=>t.MontageReceipts.Count)==8);
            Guid node=f.Writer.Capture()!.Nodes.Single(n=>n.Kind==AnimationNodeKind.Slot).Id;Check(r.Timeline[0].Events.Count(e=>e.NodeId==node)==1&&r.Timeline[2].Events.Count(e=>e.NodeId==node)==1&&r.Timeline[3].Events.All(e=>e.NodeId!=node)&&r.Timeline[6].Events.All(e=>e.NodeId!=node));
            // .4-.1 + .8-.4 is greater than .7 in binary64. Traverse beyond the actual end;
            // do not round the production clock or weaken the inactive/terminal interval assertions.
            var terminal=new AnimationSequenceCase(.8,2,[],[new(1,AnimationSequenceAssertionKind.SlotActive,m.Slots[0].Id,0)]){MontageRequests=[new(1,m.Slots[0].Id,MontageRequestKind.Play,Guid.Empty,10)]};var end=s.RunLocal(s.ProposeLocal(terminal));Check(end.Passed&&end.Timeline[0].MontageSlots.Single().IntervalCount==2&&end.Timeline[0].MontageSlots.Single().Frame.Weight==0&&end.Timeline[0].Events.Count(e=>e.NodeId==node)==2&&end.Timeline[1].Events.All(e=>e.NodeId!=node),"Actual terminal frame must retain both Notify intervals then stop.");
            Check(scene.SequenceEqual(f.Owner.Document.CaptureBytes())&&file.SequenceEqual(File.ReadAllBytes(f.File))&&state==f.Owner.Edit.State&&f.Owner.Document.World.Tick==0&&r.Timeline[0].Frame.Context.WorldId!=f.Owner.Document.World.Identity);
            s.PrepareTrusted(false);Reject(()=>s.RunLocal(id));var noRoot=s.RunLocal(s.ProposeLocal(Case(m)));Check(noRoot.Passed&&!noRoot.RootMotionSupported&&noRoot.Timeline.All(t=>t.Root is null));
        });
        yield return("M6.8-C2 real stdio exact-case approval/Slot receipt schemas/cache/TTL/revoke/queued/re-pair",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);var m=Save(f);var s=f.Writer!.Sequences;s.PrepareTrusted();Guid id=Guid.NewGuid();object proposed=new{graphId=f.Graph,caseId=id,test=AnimationSequenceCodec.Encode(Case(m))};Check(f.Call(AnimationSequenceSchemas.Propose,proposed,Guid.NewGuid()).GetProperty("isError").GetBoolean());f.ApproveUi();
            using(var locked=new FileStream(f.File,FileMode.Open,FileAccess.Read,FileShare.None))Check(!f.Call(AnimationSequenceSchemas.Propose,proposed,Guid.NewGuid()).GetProperty("isError").GetBoolean());object Input(string section,int offset=0,int limit=1)=>new{graphId=f.Graph,caseId=id,section,offset,limit};Guid request=Guid.NewGuid();Check(f.Call(AnimationSequenceSchemas.Run,Input("montage"),request).GetProperty("isError").GetBoolean());var review=s.CaptureReview(id);Reject(()=>s.Approve(review with{CaseHash="forged"},review.Fingerprint,true));s.Approve(review,review.Fingerprint,true);byte[] scene=f.Owner.Document.CaptureBytes();var state=f.Owner.Edit!.State;
            using(var locked=new FileStream(f.File,FileMode.Open,FileAccess.Read,FileShare.None))foreach(string section in new[]{"montage","requests"}){var result=f.Call(AnimationSequenceSchemas.Run,Input(section),Guid.NewGuid());Check(!result.GetProperty("isError").GetBoolean(),result.GetRawText());CharacterInspectionTests.Schema(result.GetProperty("structuredContent"),AnimationSequenceSchemas.Descriptors()[1].OutputSchema);var data=result.GetProperty("structuredContent").GetProperty("data");Check(data.GetProperty("total").GetInt32()==8&&data.GetProperty("items").GetArrayLength()==1&&data.GetProperty("nextOffset").GetInt32()==1&&!data.GetProperty("livePlay").GetBoolean()&&!data.GetProperty("collisionExecuted").GetBoolean());Check(data.GetRawText()==f.Call(AnimationSequenceSchemas.Run,Input(section),Guid.NewGuid()).GetProperty("structuredContent").GetProperty("data").GetRawText());var last=f.Call(AnimationSequenceSchemas.Run,Input(section,7),Guid.NewGuid()).GetProperty("structuredContent").GetProperty("data");Check(last.GetProperty("nextOffset").ValueKind==JsonValueKind.Null);}
            Check(!f.Call(AnimationSequenceSchemas.Run,Input("montage"),request).GetProperty("isError").GetBoolean());f.Time.Now=60000;Check(f.Call(AnimationSequenceSchemas.Run,Input("montage"),request).GetProperty("isError").GetBoolean());f.Time.Now=0;s.Approve(s.CaptureReview(id),s.CaptureReview(id).Fingerprint,true);s.Revoke();Check(f.Call(AnimationSequenceSchemas.Run,Input("montage"),request).GetProperty("isError").GetBoolean());s.Approve(s.CaptureReview(id),s.CaptureReview(id).Fingerprint,true);
            var message=new{jsonrpc="2.0",id=690821,method="tools/call",@params=new{name=AnimationSequenceSchemas.Run,arguments=new{contractVersion=2,requestId=Guid.NewGuid(),sessionId=f.Owner.Edit.SessionId,expectedRevision=f.Owner.Edit.Revision,input=Input("requests")}}};f.Client.StandardInput.WriteLine(JsonSerializer.Serialize(message,Wire.Json));f.Client.StandardInput.Flush();var response=f.Client.StandardOutput.ReadLineAsync();var watch=Stopwatch.StartNew();while(f.Owner.Endpoint!.View.QueueCount==0){if(watch.ElapsedMilliseconds>10000)throw new TimeoutException("Isolated controls queue");Thread.Sleep(1);}Check(!response.IsCompleted);s.Revoke();f.Owner.Endpoint.Pump();Check(response.Wait(10000));using(var parsed=JsonDocument.Parse(response.Result!))Check(parsed.RootElement.GetProperty("result").GetProperty("isError").GetBoolean());
            s.Approve(s.CaptureReview(id),s.CaptureReview(id).Fingerprint,true);var endpoint=f.Owner.Endpoint;var connection=endpoint.View.Connections.Single().ConnectionId;endpoint.Revoke(connection);endpoint.Pair(connection,true);Check(f.Call(AnimationSequenceSchemas.Run,Input("montage"),request).GetProperty("isError").GetBoolean());Reject(()=>s.Approve(review,review.Fingerprint,true));f.ApproveUi();s.Approve(s.CaptureReview(id),s.CaptureReview(id).Fingerprint,true);
            Check(f.Call(AnimationSequenceSchemas.Propose,new{graphId=f.Graph,caseId=id,test=AnimationSequenceCodec.Encode(Case(m) with{MontageRequests=[new(1,m.Slots[0].Id,MontageRequestKind.Play,Guid.Empty,20)]})},Guid.NewGuid()).GetProperty("isError").GetBoolean());Check(scene.SequenceEqual(f.Owner.Document.CaptureBytes())&&state==f.Owner.Edit.State&&f.Owner.Document.World.Tick==0);s.PrepareTrusted();Check(f.Call(AnimationSequenceSchemas.Run,Input("montage"),request).GetProperty("isError").GetBoolean());
        });
        yield return("M6.8-C2 complete GUI review includes all typed control rows before Agent execution",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);var m=Save(f);f.ApproveUi();Click(f,40,8);Click(f,24,12);Click(f,24,48);Click(f,50,60);var s=f.Writer!.Sequences;s.PrepareTrusted();Guid id=Guid.NewGuid();var test=new AnimationSequenceCase(.1,64,[],[]){MontageRequests=Enumerable.Range(1,64).Select(i=>new AnimationSequenceMontageRequest(i,m.Slots[0].Id,MontageRequestKind.Play,Guid.Empty,10)).ToArray()};Check(!f.Call(AnimationSequenceSchemas.Propose,new{graphId=f.Graph,caseId=id,test=AnimationSequenceCodec.Encode(test)},Guid.NewGuid()).GetProperty("isError").GetBoolean());f.Build();var select=f.View.Items.ToArray().Single(i=>i.WidgetHigh==55&&i.WidgetLow>=1000&&i.Kind==(uint)GuiItemKind.Button);Click(f,55,select.WidgetLow);Click(f,55,8);Check(f.View.Items.ToArray().Single(i=>i.WidgetHigh==55&&i.WidgetLow==12).Enabled==0);object input=new{graphId=f.Graph,caseId=id,section="requests",offset=56,limit=8};Click(f,55,12,1);Click(f,55,13);Check(f.Call(AnimationSequenceSchemas.Run,input,Guid.NewGuid()).GetProperty("isError").GetBoolean());int pages=1;while(f.View.Items.ToArray().Single(i=>i.WidgetHigh==55&&i.WidgetLow==11).Enabled==1){Click(f,55,11);Check(++pages<30);}Check(pages>1);Click(f,55,12,1);Click(f,55,13);var result=f.Call(AnimationSequenceSchemas.Run,input,Guid.NewGuid());Check(!result.GetProperty("isError").GetBoolean(),result.GetRawText());Check(result.GetProperty("structuredContent").GetProperty("data").GetProperty("items")[7].GetProperty("requestIndex").GetInt32()==63);Click(f,55,16);Check(f.Call(AnimationSequenceSchemas.Run,input,Guid.NewGuid()).GetProperty("isError").GetBoolean());
        });
        yield return("M6.8-C2 stamped typed request/closed assertion UI/paging and actual ImGui no live execution",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);var m=Save(f);f.ApproveUi();Click(f,40,8);Click(f,24,12);Click(f,24,48);Click(f,50,60);Click(f,55,2);byte[] file=File.ReadAllBytes(f.File),scene=f.Owner.Document.CaptureBytes();var state=f.Owner.Edit!.State;Text(f,60,3,m.Slots[0].Id.ToString("D"));Click(f,60,5,10);Click(f,60,6);var stale=f.Event(60,6);Click(f,60,1,2);Click(f,60,2,2);Text(f,60,4,m.Sections.Single(s=>s.Name=="Recovery").Id.ToString("D"));Click(f,60,6);Click(f,60,1,3);Click(f,60,2,1);Text(f,60,4,Guid.Empty.ToString("D"));Click(f,60,6);Text(f,60,22,m.Slots[0].Id.ToString("D"));Click(f,60,23,1);Click(f,60,24);Click(f,55,6);var s=f.Writer!.Sequences;var id=s.Pending.Single();Check(s.CaseCopy(id).MontageRequests.Length==3&&s.CaseCopy(id).Assertions.Length==1);f.View.Apply([stale],[]);f.Build();Check(s.Pending.Length==1);Click(f,55,7);Check(Encoding.UTF8.GetString(f.View.Text).Contains("passed=True"));Click(f,55,24);Check(Encoding.UTF8.GetString(f.View.Text).Contains("Jumped")&&Encoding.UTF8.GetString(f.View.Text).Contains("Cancelled"));Click(f,55,23);Check(Encoding.UTF8.GetString(f.View.Text).Contains("generation="));
            using var loader=new PluginLoader();loader.Load(plugins,[new("platform",ModuleKind.Platform,"NcmaPlatform.dll","NcmaPlatform.dll",1,0,[]),new("renderer",ModuleKind.Renderer,"NcmaRenderer.dll","NcmaRenderer.dll",1,2,["platform"]),new("gui",ModuleKind.Gui,"NcmaGui.dll","NcmaGui.dll",1,7,["platform","renderer"])]);
            using var window=new PlatformWindow(loader.Modules.Single(p=>p.Kind==ModuleKind.Platform),"M6.8-C2 isolated case",1280,720,false);using var renderer=new RendererSession(loader.Modules.Single(p=>p.Kind==ModuleKind.Renderer),window,1280,720,pureUi:true);
            using var gui=new GuiSession(loader.Modules.Single(p=>p.Kind==ModuleKind.Gui),window,Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts),"msyh.ttc"));gui.AttachRenderer(renderer);
            using var white=renderer.CreateUiImage(1,1,new byte[]{255,255,255,255});var builder=new UiDisplayListBuilder(renderer);builder.Quad(new(Guid.NewGuid(),new(0,0,1,1),Matrix3x2.Identity,new(0,0,1,1),1,true,-1),white,UiColor.Transparent);using var clear=builder.Build();
            for(int frame=0;frame<2;frame++){gui.Begin(window.Poll(),1d/60);f.Build();Check(f.View.Items.ToArray().Single(i=>i.WidgetHigh==1&&i.WidgetLow==412&&i.Kind==(uint)GuiItemKind.PanelBegin).Value==2,"Exact-case review must use the foreground panel contract.");gui.Draw(f.View.Frame,f.View.Items,f.View.Text);renderer.SubmitUi(clear,f.View.Frame.Frame,new(.02f,.03f,.04f,1));gui.RenderGpu();if(frame==1){var pixels=new byte[1280*720*4];renderer.Capture(pixels);GraphAuthoringTests.SaveBmp(Path.Combine(output,"m6-8-c2-isolated-sequence.bmp"),pixels,1280,720);}renderer.Present();}renderer.WaitIdle();Check(renderer.Stats.ValidationErrors==0&&renderer.Stats.ValidationWarnings==0&&renderer.UiStats.PureUi==1&&renderer.Stats.LiveGroups==0);
            for(int i=0;i<3;i++)Click(f,60,6);Check(f.View.Items.ToArray().Count(i=>i.WidgetHigh==60&&i.WidgetLow>=1000&&i.Kind==(uint)GuiItemKind.Button)==4);Click(f,60,10);Check(f.View.Items.ToArray().Count(i=>i.WidgetHigh==60&&i.WidgetLow>=1000&&i.Kind==(uint)GuiItemKind.Button)==2);Click(f,60,1005);Click(f,60,8);Click(f,60,1004);Click(f,60,7);Click(f,55,6);Check(s.Pending.Length==2&&s.CaseCopy(s.Pending.Single(p=>p!=id)).MontageRequests.Length==5);Check(file.SequenceEqual(File.ReadAllBytes(f.File))&&scene.SequenceEqual(f.Owner.Document.CaptureBytes())&&state==f.Owner.Edit.State&&f.Owner.Document.World.Tick==0);Click(f,55,17);Check(!f.View.Items.ToArray().Any(i=>i.WidgetHigh==60));
        });
    }
}
