using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Ncma.Animation;
using Ncma.Animation.Native;
using Ncma.Assets;
using Ncma.Assets.Authoring;
using Ncma.Editor.App;
using Ncma.Editor.Core;
using Ncma.Editor.Protocol;
using Ncma.Editor.Services;
using Ncma.Gui;
using Ncma.Interop;
using Ncma.Platform;
using Ncma.Rendering;

internal static unsafe class MontageAuthoringTests
{
    private static void Check(bool v,string reason=""){if(!v)throw new Exception("M6.8-C1 authoring: "+reason);}
    private static void Reject(Action a){try{a();}catch(Exception e)when(e is ArgumentException or InvalidOperationException or IOException or JsonException){return;}throw new Exception("Invalid Montage authoring accepted.");}
    private static JsonElement Creation(AnimationGraphDefinition d,Guid clip)
    {
        Guid slot=Guid.NewGuid(),section=Guid.NewGuid();var m=new AnimationMontageDefinition(1,Guid.NewGuid(),"Reviewed action",d.SkeletonId,[new(slot,"Body",section,10,true,false,.1,.1)],[new(section,"Attack",slot,clip,0,.2,Guid.Empty)]);
        var node=AnimationGraphNode.Create(Guid.NewGuid(),"Body Slot",AnimationNodeKind.Slot) with{SlotId=slot,PlayOnStart=false};var output=d.Nodes.Single(n=>n.Kind==AnimationNodeKind.Output);var edge=d.Links.Single(l=>l.To==output.Id);
        return AnimationGraphEdits.Operations(new{op="montage.upsert",montage=m},new{op="node.upsert",node},new{op="link.delete",id=edge.Id},new{op="link.upsert",link=new AnimationGraphLink(Guid.NewGuid(),edge.From,edge.FromPin,node.Id,"pose")},new{op="link.upsert",link=new AnimationGraphLink(Guid.NewGuid(),node.Id,"pose",output.Id,"pose")});
    }
    private static void Click(GraphInspectionTests.Fixture f,ulong high,ulong low,double value=0){f.Click(high,low,value);f.Build();}
    private static void Refresh(GraphInspectionTests.Fixture f){f.View.SynchronizeGraph();f.Build();}
    private static void Text(GraphInspectionTests.Fixture f,ulong high,ulong low,string text,uint phase=3){byte[] bytes=Encoding.UTF8.GetBytes(text);var e=f.Event(high,low);e.Phase=phase;e.TextLength=(uint)bytes.Length;f.View.Apply([e],bytes);f.Build();}
    private static void Enter(GraphInspectionTests.Fixture f){f.ApproveUi();Click(f,40,8);Click(f,24,12);Click(f,24,48);Click(f,50,6,1);Click(f,50,7);Click(f,50,8);}
    private static void Ready(GraphInspectionTests.Fixture f){Click(f,50,10);Click(f,50,52,1);Click(f,50,53);}
    internal static IEnumerable<(string,Action)> Cases(string output,string repository,string plugins)
    {
        yield return("M6.8-C1 real stdio typed Montage proposal/diff/two approvals/replay/sole Undo",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);var w=f.Writer!;Guid id=Guid.NewGuid();object input=new{graphId=f.Graph,proposalId=id,operations=Creation(w.Capture()!,f.Clip)};
            Check(f.Call(AnimationGraphAuthoringSchemas.Propose,input,Guid.NewGuid()).GetProperty("isError").GetBoolean());f.ApproveUi();byte[] before=File.ReadAllBytes(f.File),scene=f.Owner.Document.CaptureBytes();
            using(var locked=new FileStream(f.File,FileMode.Open,FileAccess.Read,FileShare.None)){var p=f.Call(AnimationGraphAuthoringSchemas.Propose,input,Guid.NewGuid());Check(!p.GetProperty("isError").GetBoolean(),p.GetRawText());var result=p.GetProperty("structuredContent");CharacterInspectionTests.Schema(result,AnimationGraphAuthoringSchemas.Descriptor.OutputSchema);var diff=result.GetProperty("data");Check(diff.GetProperty("added").GetInt32()==6&&diff.GetProperty("removed").GetInt32()==1&&diff.GetProperty("updated").GetInt32()==0,"Montage/Slot/Section are separate reviewed rows");}
            Check(before.SequenceEqual(File.ReadAllBytes(f.File))&&f.Owner.Edit!.State.UndoCount==0&&scene.SequenceEqual(f.Owner.Document.CaptureBytes()));Guid request=Guid.NewGuid();ulong revision=f.Owner.Edit!.Revision;var tx=new{proposalId=id,expectedAssetRevision=f.Owner.Assets!.Clock.Revision};
            Check(f.Call(AnimationGraphCommands.CapabilityName,tx,request,revision).GetProperty("isError").GetBoolean());var controller=new EditorAuthorizationController(f.Workspace);var page=controller.Capture()!;var pending=page.Proposals.Single();controller.Approve(page,pending.Scope.Id,pending.Fingerprint,true,null);
            Check(f.Call(AnimationGraphCommands.CapabilityName,tx,request,revision).GetProperty("isError").GetBoolean());var review=w.CaptureReview(id);Reject(()=>w.Approve(review,review.Fingerprint,review.Graph,false));w.Approve(review,review.Fingerprint,review.Graph,true);
            Check(!f.Call(AnimationGraphCommands.CapabilityName,tx,request,revision).GetProperty("isError").GetBoolean());Check(f.Call(AnimationGraphCommands.CapabilityName,tx,request,revision).GetProperty("structuredContent").GetProperty("replayed").GetBoolean());w.Synchronize();byte[] saved=File.ReadAllBytes(f.File);Check(w.Capture()!.Montage!.Sections.Single().Name=="Attack"&&f.Owner.Edit.State.UndoCount==1&&scene.SequenceEqual(f.Owner.Document.CaptureBytes()));
            f.Workspace.History(f.Workspace.Stamp,false);w.Synchronize();Check(before.SequenceEqual(File.ReadAllBytes(f.File)));f.Workspace.History(f.Workspace.Stamp,true);w.Synchronize();Check(saved.SequenceEqual(File.ReadAllBytes(f.File)));
            f.ApproveUi();var m=w.Capture()!.Montage!;Guid update=Guid.NewGuid();var changed=f.Call(AnimationGraphAuthoringSchemas.Propose,new{graphId=f.Graph,proposalId=update,operations=AnimationGraphEdits.Operations(new{op="montage.slot.upsert",slot=m.Slots[0] with{Priority=23}},new{op="montage.section.upsert",section=m.Sections[0] with{Name="Recovery"}})},Guid.NewGuid());Check(!changed.GetProperty("isError").GetBoolean(),changed.GetRawText());Check(changed.GetProperty("structuredContent").GetProperty("data").GetProperty("updated").GetInt32()==2,"Every typed Slot/Section change must appear in diff");w.CancelProposal(update);w.Revoke();Reject(()=>f.Workspace.History(f.Workspace.Stamp,false));
        });
        yield return("M6.8-C1 typed Slot/Section UI, stamped endpoint drag/cancel/strict repair/save",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);var w=f.Writer!;byte[] before=File.ReadAllBytes(f.File),scene=f.Owner.Document.CaptureBytes();Enter(f);Click(f,50,89);Check(w.Capture()!.Montage is not null);Click(f,50,602,42);Check(w.Capture()!.Montage!.Slots.Single().Priority==42);
            var stale=f.Event(59,2);Text(f,59,2,".1 .5 0",1);Text(f,59,2,".3 .5 0",2);Text(f,59,2,".4 .5 0",3);Check(w.Capture()!.Montage!.Sections.Single().End==.4);byte[] draft=AnimationGraphCodec.Encode(w.Capture()!);stale.Phase=3;f.View.Apply([stale],[]);f.Build();Check(draft.SequenceEqual(AnimationGraphCodec.Encode(w.Capture()!)));
            var entry=w.Capture()!.Montage!.Sections.Single();w.ApplyDraft(AnimationGraphEdits.Operations(Enumerable.Range(0,5).Select(i=>(object)new{op="montage.section.upsert",section=entry with{Id=Guid.NewGuid(),Name="Draft section "+i}}).ToArray()));Refresh(f);Check(f.View.Items.ToArray().Count(i=>i.WidgetHigh==59&&i.Kind==(uint)GuiItemKind.CanvasRect)==4,"First track page must show4 rows");Click(f,50,105);Check(f.View.Items.ToArray().Count(i=>i.WidgetHigh==59&&i.Kind==(uint)GuiItemKind.CanvasRect)==2,"Second track page must show remaining2 rows");Click(f,50,104);
            Click(f,50,60);Check(f.View.Items.ToArray().Any(i=>i.WidgetHigh==59&&i.WidgetLow==2)&&f.View.Items.ToArray().Any(i=>i.WidgetHigh==55&&i.WidgetLow==2),"Track and sequence panel IDs independent");Click(f,55,17);
            Check(before.SequenceEqual(File.ReadAllBytes(f.File))&&f.Owner.Edit!.State.UndoCount==0);Click(f,50,9);Check(w.Capture()!.Montage is null&&before.SequenceEqual(File.ReadAllBytes(f.File)));
            Click(f,50,8);Click(f,50,89);Click(f,50,103);var second=w.Capture()!.Montage!.Sections.Single(s=>s.Id!=w.Capture()!.Montage!.Slots.Single().EntrySection);Reject(()=>w.PrepareLocal());
            var first=w.Capture()!.Montage!.Sections.Single(s=>s.Id==w.Capture()!.Montage!.Slots.Single().EntrySection);w.ApplyDraft(AnimationGraphEdits.Operations(new{op="montage.section.upsert",section=first with{NextSection=second.Id}}));Refresh(f);Text(f,50,600,"Recovery");Ready(f);Click(f,50,54);Check(w.Capture()!.Montage!.Sections.Any(s=>s.Name=="Recovery")&&f.Owner.Edit!.State.UndoCount==1&&scene.SequenceEqual(f.Owner.Document.CaptureBytes()));
            Click(f,50,11);Check(w.Capture()!.Montage is null&&before.SequenceEqual(File.ReadAllBytes(f.File)));Click(f,50,12);Check(w.Capture()!.Montage!.Sections.Length==2&&f.Owner.Document.World.Tick==0);
        });
        yield return("M6.8-C1 typed proposal TTL/revoke/queued/re-pair and actual NCA interval/generation rejection",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);var w=f.Writer!;f.ApproveUi();byte[] before=File.ReadAllBytes(f.File);var ops=Creation(w.Capture()!,f.Clip);Guid id=Guid.NewGuid();
            object Input(Guid p)=>new{graphId=f.Graph,proposalId=p,operations=ops};Check(!f.Call(AnimationGraphAuthoringSchemas.Propose,Input(id),Guid.NewGuid()).GetProperty("isError").GetBoolean());var review=w.CaptureReview(id);w.Approve(review,review.Fingerprint,review.Graph,true);f.Time.Now=60000;Reject(()=>w.CaptureReview(id));f.Time.Now=0;w.Reads.Revoke();Reject(()=>w.CaptureReview(id));w.CancelProposal(id);f.ApproveUi();id=Guid.NewGuid();Check(!f.Call(AnimationGraphAuthoringSchemas.Propose,Input(id),Guid.NewGuid()).GetProperty("isError").GetBoolean());review=w.CaptureReview(id);var endpoint=f.Owner.Endpoint!;var connection=endpoint.View.Connections.Single().ConnectionId;endpoint.Revoke(connection);endpoint.Pair(connection,true);Reject(()=>w.Approve(review,review.Fingerprint,review.Graph,true));w.CancelProposal(id);f.ApproveUi();
            var message=new{jsonrpc="2.0",id=789123,method="tools/call",@params=new{name=AnimationGraphAuthoringSchemas.Propose,arguments=new{contractVersion=2,requestId=Guid.NewGuid(),sessionId=f.Owner.Edit!.SessionId,expectedRevision=f.Owner.Edit.Revision,input=Input(Guid.NewGuid())}}};
            f.Client.StandardInput.WriteLine(JsonSerializer.Serialize(message,Wire.Json));f.Client.StandardInput.Flush();var response=f.Client.StandardOutput.ReadLineAsync();var watch=Stopwatch.StartNew();while(endpoint.View.QueueCount==0){if(watch.ElapsedMilliseconds>10000)throw new TimeoutException("Montage proposal queue");Thread.Sleep(1);}Check(!response.IsCompleted);w.Reads.Revoke();endpoint.Pump();Check(response.Wait(10000));using(var parsed=JsonDocument.Parse(response.Result!))Check(parsed.RootElement.GetProperty("result").GetProperty("isError").GetBoolean());Check(before.SequenceEqual(File.ReadAllBytes(f.File))&&w.Pending.Length==0&&f.Owner.Edit.State.UndoCount==0);
            w.ApproveFileWrite(w.Stamp,w.Path!,f.Graph,true);w.Begin(w.Stamp);w.ApplyDraft(ops);var section=w.Capture()!.Montage!.Sections.Single();w.ApplyDraft(AnimationGraphEdits.Operations(new{op="montage.section.upsert",section=section with{End=600}}));id=w.PrepareLocal();Reject(()=>w.CaptureReview(id));Check(before.SequenceEqual(File.ReadAllBytes(f.File)));w.Cancel();w.Begin(w.Stamp);w.ApplyDraft(ops);id=w.PrepareLocal();review=w.CaptureReview(id);w.Approve(review,review.Fingerprint,review.Graph,true);
            string metadata=Path.Combine(f.Root,"assets/procedural.fbx.ncmeta");var record=AssetRecordCodec.Decode(File.ReadAllBytes(metadata));var generation=record.Generation!;string next=generation.RelativePath.Replace("/1-","/2-",StringComparison.Ordinal);File.Copy(Path.Combine(f.Root,generation.RelativePath),Path.Combine(f.Root,next));File.WriteAllBytes(metadata,AssetRecordCodec.Encode(record with{Generation=generation with{Number=2,RelativePath=next}}));Reject(()=>w.CommitLocal(id));Check(before.SequenceEqual(File.ReadAllBytes(f.File))&&f.Owner.Edit.State.UndoCount==0);
        });
        yield return("M6.8-C1 real ImGui Section/Notify track and same NCA Slot skin preview/drain",()=>{
            using var f=new GraphInspectionTests.Fixture(output,repository,true);byte[] scene=f.Owner.Document.CaptureBytes();Guid world=f.Owner.Document.World.Identity;
            using var loader=new PluginLoader();loader.Load(plugins,[new("platform",ModuleKind.Platform,"NcmaPlatform.dll","NcmaPlatform.dll",1,0,[]),new("renderer",ModuleKind.Renderer,"NcmaRenderer.dll","NcmaRenderer.dll",1,2,["platform"]),new("gui",ModuleKind.Gui,"NcmaGui.dll","NcmaGui.dll",1,7,["platform","renderer"])]);
            using var window=new PlatformWindow(loader.Modules.Single(m=>m.Kind==ModuleKind.Platform),"M6.8-C1 Montage",1280,720,false);using var renderer=new RendererSession(loader.Modules.Single(m=>m.Kind==ModuleKind.Renderer),window,1280,720);string path=Path.Combine(plugins,"NcmaAnimationKernel.dll");using var kernel=new PoseKernel(path,Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))),blendSupport:true);using var preview=new EditorAnimationGraphPreview(renderer,()=>kernel);using var gui=new GuiSession(loader.Modules.Single(m=>m.Kind==ModuleKind.Gui),window,Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts),"msyh.ttc"));gui.AttachRenderer(renderer);f.View.AttachGraphAuthoring(f.Writer!,preview);
            Enter(f);Click(f,50,89);var w=f.Writer!;var slotNode=w.Capture()!.Nodes.Single(n=>n.Kind==AnimationNodeKind.Slot);var choice=f.View.Items.ToArray().Single(i=>i.WidgetHigh==51&&i.Kind==(uint)GuiItemKind.SelectionButton&&Encoding.UTF8.GetString(f.View.Text.Slice((int)i.LabelOffset,(int)i.LabelLength)).EndsWith(slotNode.Name,StringComparison.Ordinal));Click(f,51,choice.WidgetLow);Click(f,50,604,1);Check(w.Capture()!.Nodes.Single(n=>n.Kind==AnimationNodeKind.Slot).PlayOnStart);w.ApplyDraft(AnimationGraphEdits.Operations(new{op="event.upsert",marker=new AnimationEventMarker(Guid.NewGuid(),f.Clip,.05,"HitWindow data")}));Refresh(f);Click(f,50,102);string sectionName=w.Capture()!.Montage!.Sections.Single().Name;var row=f.View.Items.ToArray().Single(i=>i.WidgetHigh==50&&i.Kind==(uint)GuiItemKind.Button&&i.WidgetLow>=10000&&Encoding.UTF8.GetString(f.View.Text.Slice((int)i.LabelOffset,(int)i.LabelLength)).EndsWith(sectionName,StringComparison.Ordinal));Click(f,50,row.WidgetLow);Ready(f);Click(f,50,55);Check(preview.Prepared&&preview.WorldId!=world&&f.View.Items.ToArray().Any(i=>i.WidgetHigh==50&&i.WidgetLow==603&&i.Kind==(uint)GuiItemKind.Number));
            try{for(int i=0;i<8;i++){gui.Begin(window.Poll(),1d/60);f.Build();var frame=f.View.AttachGraphPreview(f.View.Frame.Frame);Check(f.View.GraphPreviewSubmitted&&f.View.Items.ToArray().Any(v=>v.WidgetHigh==59&&v.Kind==(uint)GuiItemKind.CanvasLines));gui.Draw(frame,f.View.Items,f.View.Text);gui.RenderGpu();if(i==7){byte[] pixels=new byte[1280*720*4];renderer.Capture(pixels);GraphAuthoringTests.SaveBmp(Path.Combine(output,"m6-8-c1-montage-authoring.bmp"),pixels,1280,720);}renderer.Present();preview.Advance(1d/60);}Check(preview.GraphFrame!.Value.Context.Tick==8&&renderer.Stats.ValidationErrors==0&&renderer.Stats.ValidationWarnings==0&&scene.SequenceEqual(f.Owner.Document.CaptureBytes())&&f.Owner.Document.World.Identity==world&&f.Owner.Document.World.Tick==0);}
            finally{preview.Close();}Check(kernel.Statistics.Rigs==0&&kernel.Statistics.Clips==0&&renderer.SkinStats.Meshes==0);
        });
    }
}
