<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ncma.Managed/Ncma.Managed.csproj" />
    <ProjectReference Include="../Ncma.Scene/Ncma.Scene.csproj" />
    <InternalsVisibleTo Include="Ncma.Editor.Services" />
    <InternalsVisibleTo Include="Ncma.Gameplay.Tests" />
    <InternalsVisibleTo Include="Ncma.Movement" />
  </ItemGroup>
</Project>
