<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><TreatWarningsAsErrors>true</TreatWarningsAsErrors></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Ncma.Rendering/Ncma.Rendering.csproj" /><ProjectReference Include="../Ncma.Scene.Rendering/Ncma.Scene.Rendering.csproj" /></ItemGroup>
</Project>
