<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><TreatWarningsAsErrors>true</TreatWarningsAsErrors><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup><ItemGroup><ProjectReference Include="../Ncma.Rendering/Ncma.Rendering.csproj" /><ProjectReference Include="../Ncma.Rendering.Scene/Ncma.Rendering.Scene.csproj" /><ProjectReference Include="../Ncma.Gui/Ncma.Gui.csproj" /><ProjectReference Include="../Ncma.Editor.Services/Ncma.Editor.Services.csproj" /></ItemGroup></Project>
