using System.Text;
using Ncma.Animation;
internal static class MontageDataTests
{
    private static void Check(bool v){if(!v)throw new Exception("M6.8-A montage assertion.");}
    private static void Reject(Action action){try{action();}catch(Exception e)when(e is ArgumentException or InvalidOperationException or System.Text.Json.JsonException){return;}throw new Exception("Invalid montage accepted.");}
    internal static AnimationMontageDefinition Definition(){Guid slot=Guid.NewGuid(),a=Guid.NewGuid(),b=Guid.NewGuid(),clip=Guid.NewGuid();return new(1,Guid.NewGuid(),"动作编排",Guid.NewGuid(),[new(slot,"Body",a,10,true,true,.1,.2)],[new(a,"Attack",slot,clip,.1,.4,b),new(b,"Recovery",slot,clip,.4,.8,Guid.Empty)]);}
    internal static AnimationMontageProgram Compile(AnimationMontageDefinition d)=>new(d,7,d.Sections.Select(s=>s.ClipId).Distinct().Select(id=>new AnimationClipDescriptor(id,d.SkeletonId,7,1)).ToArray());
    public static void Add(List<(string,Action)> tests)
    {
        tests.Add(("M6.8-A strict closed Montage data/canonical order/owned metadata and allowed Section cycles",()=>{var d=Definition();byte[] bytes=AnimationMontageCodec.Encode(d);Check(bytes.SequenceEqual(AnimationMontageCodec.Encode(d with{Sections=d.Sections.Reverse().ToArray()})));var p=Compile(d);d.Sections[0]=d.Sections[0] with{End=.2};Check(p.CopyDefinition().Sections.Single(s=>s.Name=="Attack").End==.4);var copy=p.CopyDefinition();copy.Slots[0]=copy.Slots[0] with{Name="changed"};Check(p.RequireSlot(copy.Slots[0].Id).Name=="Body");var cycle=Definition();cycle=cycle with{Sections=cycle.Sections.Select(s=>s.NextSection==Guid.Empty?s with{NextSection=cycle.Slots[0].EntrySection}:s).ToArray()};Check(Compile(cycle).CopyDefinition().Sections.Length==2); }));
        tests.Add(("M6.8-A Montage invalid intervals/aliases/Slot membership/reachability/metadata durations",()=>{var d=Definition();Reject(()=>AnimationMontageCodec.Encode(d with{Sections=d.Sections.Select(s=>s with{End=s.Start}).ToArray()}));Reject(()=>AnimationMontageCodec.Encode(d with{Sections=d.Sections.Select(s=>s with{End=double.NaN}).ToArray()}));Reject(()=>AnimationMontageCodec.Encode(d with{Slots=[d.Slots[0] with{Priority=256}]}));Reject(()=>AnimationMontageCodec.Encode(d with{Slots=[d.Slots[0] with{EntrySection=Guid.NewGuid()}]}));Reject(()=>AnimationMontageCodec.Encode(d with{Sections=d.Sections.Select(s=>s with{NextSection=Guid.Empty}).ToArray()}));Reject(()=>AnimationMontageCodec.Encode(d with{Sections=d.Sections.Select(s=>s with{ClipId=d.AssetId}).ToArray()}));Reject(()=>new AnimationMontageProgram(d,7,[]));Reject(()=>new AnimationMontageProgram(d,7,[new(d.Sections[0].ClipId,d.SkeletonId,8,1)]));Reject(()=>new AnimationMontageProgram(d,7,[new(d.Sections[0].ClipId,d.SkeletonId,7,.5)]));}));
        tests.Add(("M6.8-A Montage JSON missing/duplicate/unknown/version and byte/text budgets",()=>{var d=Definition();string json=Encoding.UTF8.GetString(AnimationMontageCodec.Encode(d));foreach(string invalid in new[]{json.Replace("\"version\":1","\"version\":0"),json.Replace("\"version\":1,",""),json.Insert(1,"\"version\":1,"),json.Insert(1,"\"worldHandle\":1,"),json.Replace("\"rootMotion\":true,",""),"null"})Reject(()=>AnimationMontageCodec.Decode(Encoding.UTF8.GetBytes(invalid)));Reject(()=>AnimationMontageCodec.Decode(new byte[AnimationMontageCodec.MaxBytes+1]));Reject(()=>AnimationMontageCodec.Encode(d with{Name="\ud800"}));AnimationMontageCodec.RequireExtension("x.NCMAMONTAGE");Reject(()=>AnimationMontageCodec.RequireExtension("x.ncmaanim"));}));
    }
}
