<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><TreatWarningsAsErrors>true</TreatWarningsAsErrors></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Ncma.Animation.Native/Ncma.Animation.Native.csproj" /><ProjectReference Include="../Ncma.Asset.Import/Ncma.Asset.Import.csproj" /><ProjectReference Include="../Ncma.Gameplay/Ncma.Gameplay.csproj" /></ItemGroup>
</Project>
