<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Ncma.Assets/Ncma.Assets.csproj" /><ProjectReference Include="../Ncma.Animation/Ncma.Animation.csproj" /></ItemGroup>
</Project>
