<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schemas/*.json" />
    <InternalsVisibleTo Include="Ncma.Assets.Runtime" />
    <InternalsVisibleTo Include="Ncma.Rendering" />
  </ItemGroup>
</Project>
