from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def inspect_project(root: Path) -> dict[str, Any]:
    root = root.resolve()
    return {
        "schema_version": 10,
        "engine": "NcmaEngine",
        "root": str(root),
        "languages": {
            "scope": "target_architecture",
            "core": "C#/.NET 8",
            "gameplay": ["C#/.NET 8"],
            "native_plugins": "C++20",
            "tools_and_ai": "Python 3.10+",
        },
        "architecture": {
            "direction": "managed_runtime_python_modules_native_plugins",
            "migration_status": "managed_document_commands_native_ImGui_shell",
            "target": {
                "application_host": "C#",
                "world_and_components": "C#",
                "system_scheduler": "C#",
                "editor_business_logic": "C#",
                "scene_asset_metadata_serialization": "C#",
                "gameplay": "C#",
                "python_role": "independent_ai_and_specialized_modules",
                "native_role": "performance_critical_plugins_only",
                "networking": "independent_C#_service",
            },
            "implemented": {
                "scope": "production_default_entry",
                "application_host": "C++",
                "world_and_components": "C#_Runtime.World",
                "editor_business_logic": "C#_Editor.Core_with_C++_ImGui_shell",
                "managed_world_is_native_wrapper": False,
                "managed_application_host": False,
                "managed_authoritative_world": True,
                "independent_renderer_physics_plugins": False,
                "gameplay_languages": ["C#/.NET 8"],
            },
            "candidate": {
                "scope": "M2.1-M2.7_candidate_H7_incomplete",
                "h8_accepted": False,
                "consolidated_cleanup_completed": False,
                "managed_runtime_service": True,
                "player_project": "managed/Ncma.Player.App",
                "player_headless_implemented": True,
                "player_graphical_scope": "DX11_reference_scene_only",
                "player_framework_dependent_package": True,
                "player_self_contained_verified": False,
                "player_h7_complete": False,
                "player_report": "docs/M2_7_DELIVERY_REPORT.md",
                "entry_project": "managed/Ncma.Editor.App",
                "application_host": "C#",
                "managed_application_host": True,
                "native_module_abi": {"major": 1, "minor": 0},
                "independent_platform_plugin": True,
                "independent_gui_plugin": True,
                "independent_renderer_plugin": True,
                "independent_physics_plugin": True,
                "physics_module_abi": {"major": 1, "minor": 1},
                "physics_scope": "thin_native_solver_managed_physics_service_2D_3D",
                "managed_physics_service": True,
                "physics_service_policy": ["world_lifecycle", "pause_single_step", "bounded_velocity_staging", "copied_snapshots", "diagnostics_profiles"],
                "physics_mcp_tools_implemented": False,
                "physics_scene_integration": False,
                "physics_automated_gate_passed": True,
                "physics_report": "docs/M2_6_DELIVERY_REPORT.md",
                "renderer_scope": "DX11_reference_scene_only",
                "vulkan_renderer_implemented": False,
                "editor_business_panels_migrated": True,
                "live_editor_mcp_migrated": True,
                "editor_business_migration": "candidate_A_B_C_D_E_F_implemented_manual_gate_pending",
                "fbx_preview_migration": "managed_state_history_wireframe_orbit_report_ABI2",
                "fbx_character_abi": 2,
                "fbx_preview_history_owner": "C#",
                "fbx_preview_history_limit": 8,
                "fbx_preview_wireframe_migrated": True,
                "fbx_preview_scene_integration": False,
                "fbx_preview_report": "docs/M2_5_FBX_DELIVERY_REPORT.md",
                "editor_business_slice": ["document_commands", "paged_flat_objects", "inspector_drafts", "play_controls", "trusted_mcp_approval_ui", "large_component_json_pages", "reference_render_controls", "fbx_preview_commands", "action_preview_ABI2", "local_preferences", "file_picker_shortcuts", "native_console_pages"],
                "gui_module_abi": {"major": 1, "minor": 2},
                "renderer_module_abi": {"major": 1, "minor": 1},
                "animation_kernel_abi": 2,
                "animation_preview_policy_owner": "C#_or_isolated_Python_tool",
                "local_preferences_history": "separate_user_settings_domain",
                "native_console_log_reader": "copied_spdlog_pages_v1",
                "editor_business_report": "docs/M2_5_H5_DELIVERY_REPORT.md",
                "automated_gate_passed": True,
                "manual_acceptance_passed": False,
                "h5_accepted": False,
                "visible_third_party_client_acceptance_passed": False,
                "default_entry_switched": False,
                "report": "docs/M2_3_4_TEST_REPORT.md",
            },
        },
        "managed_runtime": {
            "project": "managed/Ncma.Runtime",
            "status": "authoritative_world_editor_bridge",
            "authoritative_owner": "C#",
            "native_dependency": False,
            "python_dependency": False,
            "editor_integrated": True,
            "replaces_legacy_world": True,
            "empty_objects_optional_transform": True,
            "registered_value_components": True,
            "schema_support": "closed_objects_scalars_local_defs",
            "full_json_schema_validation": False,
            "generic_component_queries": False,
            "storage": "boxed_type_dictionary_correctness_foundation",
            "fixed_step_systems": True,
            "fixed_step_structural_commands": False,
            "managed_behaviour_lifecycle": True,
            "snapshot_format": "scene_document_json_v1",
            "complete_scene_document": True,
            "complete_snapshot_native_undo_and_play": False,
            "complete_snapshot_managed_undo_and_play": True,
            "legacy_scene_import": False,
            "scene_file_codec_owner": "C#",
            "edit_session_live_editor_integrated": True,
            "editor_project": "managed/Ncma.Editor.Core",
            "editor_history_owner": "C#",
            "native_scene_command_stack": False,
            "interaction_drafts": True,
            "dirty_content_fingerprint": True,
            "play_edit_document_frozen": True,
            "world_runner_editor_integrated": True,
            "snapshot_restores_invalidate_all_handles": True,
            "undoable_atomic_scene_transactions": True,
        },
        "python_modules": {
            "role": "independent_ai_and_specialized_modules",
            "plugin_development_option": True,
            "gameplay_scripting": False,
            "owns_game_objects": False,
            "recommended_default_transport": "grpc_worker",
            "transport_selection_finalized": False,
            "transport_neutral_contract_implemented": False,
            "ai_worker_implemented": False,
            "transports": {
                "pythonnet": {"mode": "in_process_opt_in", "implemented": False},
                "grpc": {"mode": "out_of_process_recommended", "implemented": False},
                "zeromq": {"mode": "out_of_process_optional", "implemented": False},
            },
            "result_application": "C#_validated_commands_at_tick_boundary",
            "runtime_result_application_implemented": False,
        },
        "gameplay": {
            "policy": "csharp_only",
            "current_runtime_policy": "csharp_only",
            "csharp_only_runtime_enforced": True,
            "legacy_compatibility_retained": False,
            "python_gameplay_removed": True,
            "shared_native_core": False,
            "project_language_selection_implemented": False,
            "backends": {
                "csharp": {
                    "reference": "ProwlEngine",
                    "status": "integrated",
                    "scene_binding": True,
                    "fixed_update_scheduler": True,
                },
            },
            "play_session": {
                "project": "managed/Ncma.Gameplay",
                "owner": "C#",
                "fixed_delta_seconds": 1.0 / 60.0,
                "max_steps_per_frame": 8,
                "strict_and_interactive_time_policies": True,
                "pause_resume_single_step": True,
                "faulted_requires_stop_restart": True,
                "on_update_world_access": "read_only",
                "input_snapshot_implemented": True,
                "render_interpolation_implemented": True,
                "runtime_structural_commands_implemented": True,
                "transactional_signal_consumption_implemented": True,
                "reload_preflight_implemented": True,
            },
            "object_language_selection_implemented": False,
            "language_selection_point": "fixed_csharp",
            "binding_language_selection_implemented": False,
            "mixed_language_behaviours": False,
            "language_change_implemented": False,
            "scene_format_version": 1,
            "standalone_game_export": False,
            "world_access": {
                "scope": "csharp_managed_world",
                "native_api_version": None,
                "scene_host_bridge_version": 6,
                "safe_runtime_references": True,
                "uuid_lookup": "indexed",
                "transform_batch_read_write": True,
                "batch_and_queue_capacity": 4096,
                "editor_shared_update_commit": False,
                "managed_play_session_commit": True,
                "read_visibility": "committed_state",
                "write_conflict_policy": "last_submission_wins",
                "typed_signal_mailboxes": True,
                "signal_delivery": "after_commit_explicit_poll",
                "threading": "world_owner_thread_only",
                "direct_foreign_script_calls": False,
                "writable_native_memory_views": False,
                "generic_component_batches": False,
                "spawn_despawn_commands": True,
            },
        },
        "render_backends": ["Direct3D11", "Vulkan"],
        "render_backend_status": {"Direct3D11": "preview_implemented", "Vulkan": "probe_only"},
        "scene": {
            "authoritative_owner": "C#_Runtime.World",
            "object_api": "GameObject",
            "node_frontend_api": False,
            "native_object_api_version": None,
            "native_plugin_abi_version": 2,
            "gameplay_host_bridge_version": 5,
            "legacy_native_exports": False,
            "format_version": 1,
            "organization": "flat_object_list",
            "parent_child_ownership": False,
            "transform_inheritance": False,
            "file_extension": ".ncmascene",
            "legacy_scene_versions_readable": [],
            "legacy_scene_compatibility": False,
            "atomic_file_save": True,
            "general_component_serialization": True,
            "complete_in_memory_component_snapshots": True,
            "document_project": "managed/Ncma.Scene",
            "document_snapshot_version": 1,
            "world_asset_separation": False,
        },
        "agent_contract": {
            "format": "JSON Schema capabilities",
            "mutation_risks": ["read_only", "reversible", "destructive"],
            "managed_gateway": "C#_Editor.Core_EditSession",
            "managed_contract_version": 2,
            "managed_gateway_implemented": True,
            "managed_gateway_transport_implemented": True,
            "default_permission": "read_only",
            "revision_guards": True,
            "bounded_idempotency_cache": True,
            "destructive_uuid_authorization": True,
            "managed_capabilities": [
                "ncma.capabilities.list", "ncma.engine.component_types", "ncma.scene.inspect",
                "ncma.scene.validate", "ncma.scene.transaction", "ncma.scene.delete_object",
                "ncma.history.undo", "ncma.history.redo",
                "ncma.scene.object.inspect", "ncma.engine.behaviour_types",
            ],
            "domains": {
                "scene": "active_editor_scoped_MCP_owner_thread",
                "animation": "existing_isolated_native_preview_MCP",
                "ui": "model_only_no_editing_gateway",
                "tools": "existing_CLI_inspect_FBX_animation_MCP",
                "engine_extensions": "trusted_managed_component_registration_only",
            },
            "arbitrary_code_execution": False,
            "project_file_mutation_gateway": False,
        },
        "animation": {
            "runtime": "C++ immutable numerical kernels; C# and isolated Python tool own clocks/policy/history",
            "native_abi": 2,
            "scene_component": False,
            "model_import": True,
            "model_import_formats": ["FBX"],
            "character_resource_abi": 2,
            "character_inspection_owner": "caller_owned_buffers",
            "gpu_skinning": False,
        },
        "mcp": {
            "transport": "stdio",
            "protocol_version": "2025-11-25",
            "entrypoint": "python -m ncma_tools.cli mcp --root <project>",
            "scope": "isolated_animation_preview",
            "live_editor_connection": False,
            "default_permission": "read_only",
            "mutation_opt_in": "--allow-mutations",
            "tool_prefix": "ncma.animation.",
        },
        "editor_mcp": {
            "transport": "stdio_to_local_windows_named_pipe",
            "protocol_version": "2025-11-25",
            "ipc_version": 1,
            "entrypoint": "dotnet out/managed/editor-mcp/Ncma.Editor.Mcp.dll --descriptor <selected-instance.json>",
            "live_editor_connection": True,
            "enabled_by_default": False,
            "human_pairing_required": True,
            "default_permission": "read_only",
            "remote_mutations_implemented": True,
            "bounded_owner_thread_queue": True,
            "trusted_scope_grants_implemented": True,
        },
        "paths": {
            "native": str(root / "engine" / "source" / "runtime"),
            "managed": str(root / "managed" / "Ncma.Managed"),
            "python": str(root / "python"),
        },
    }


def write_manifest(root: Path, output: Path) -> None:
    output.write_text(
        json.dumps(inspect_project(root), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
