from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def inspect_project(root: Path) -> dict[str, Any]:
    root = root.resolve()
    return {
        "schema_version": 8,
        "engine": "NcmaEngine",
        "root": str(root),
        "languages": {
            "scope": "target_architecture",
            "core": "C#/.NET 8",
            "gameplay": ["C#/.NET 8"],
            "native_plugins": "C++20",
            "tools_and_ai": "Python 3.10+",
        },
        "architecture": {
            "direction": "managed_runtime_python_modules_native_plugins",
            "migration_status": "managed_document_commands_native_ImGui_shell",
            "target": {
                "application_host": "C#",
                "world_and_components": "C#",
                "system_scheduler": "C#",
                "editor_business_logic": "C#",
                "scene_asset_metadata_serialization": "C#",
                "gameplay": "C#",
                "python_role": "independent_ai_and_specialized_modules",
                "native_role": "performance_critical_plugins_only",
                "networking": "independent_C#_service",
            },
            "implemented": {
                "application_host": "C++",
                "world_and_components": "C#_Runtime.World",
                "editor_business_logic": "C#_Editor.Core_with_C++_ImGui_shell",
                "managed_world_is_native_wrapper": False,
                "managed_application_host": False,
                "managed_authoritative_world": True,
                "independent_renderer_physics_plugins": False,
                "gameplay_languages": ["C#/.NET 8"],
            },
        },
        "managed_runtime": {
            "project": "managed/Ncma.Runtime",
            "status": "authoritative_world_editor_bridge",
            "authoritative_owner": "C#",
            "native_dependency": False,
            "python_dependency": False,
            "editor_integrated": True,
            "replaces_legacy_world": True,
            "empty_objects_optional_transform": True,
            "registered_value_components": True,
            "schema_support": "closed_objects_scalars_local_defs",
            "full_json_schema_validation": False,
            "generic_component_queries": False,
            "storage": "boxed_type_dictionary_correctness_foundation",
            "fixed_step_systems": True,
            "fixed_step_structural_commands": False,
            "managed_behaviour_lifecycle": True,
            "snapshot_format": "scene_document_json_v1",
            "complete_scene_document": True,
            "complete_snapshot_native_undo_and_play": False,
            "complete_snapshot_managed_undo_and_play": True,
            "legacy_scene_import": False,
            "scene_file_codec_owner": "C#",
            "edit_session_live_editor_integrated": True,
            "editor_project": "managed/Ncma.Editor.Core",
            "editor_history_owner": "C#",
            "native_scene_command_stack": False,
            "interaction_drafts": True,
            "dirty_content_fingerprint": True,
            "play_edit_document_frozen": True,
            "world_runner_editor_integrated": False,
            "snapshot_restores_invalidate_all_handles": True,
            "undoable_atomic_scene_transactions": True,
        },
        "python_modules": {
            "role": "independent_ai_and_specialized_modules",
            "plugin_development_option": True,
            "gameplay_scripting": False,
            "owns_game_objects": False,
            "recommended_default_transport": "grpc_worker",
            "transport_selection_finalized": False,
            "transport_neutral_contract_implemented": False,
            "ai_worker_implemented": False,
            "transports": {
                "pythonnet": {"mode": "in_process_opt_in", "implemented": False},
                "grpc": {"mode": "out_of_process_recommended", "implemented": False},
                "zeromq": {"mode": "out_of_process_optional", "implemented": False},
            },
            "result_application": "C#_validated_commands_at_tick_boundary",
            "runtime_result_application_implemented": False,
        },
        "gameplay": {
            "policy": "csharp_only",
            "current_runtime_policy": "csharp_only",
            "csharp_only_runtime_enforced": True,
            "legacy_compatibility_retained": False,
            "python_gameplay_removed": True,
            "shared_native_core": False,
            "project_language_selection_implemented": False,
            "backends": {
                "csharp": {
                    "reference": "ProwlEngine",
                    "status": "integrated",
                    "scene_binding": True,
                    "fixed_update_scheduler": False,
                },
            },
            "object_language_selection_implemented": False,
            "language_selection_point": "fixed_csharp",
            "binding_language_selection_implemented": False,
            "mixed_language_behaviours": False,
            "language_change_implemented": False,
            "scene_format_version": 1,
            "standalone_game_export": False,
            "world_access": {
                "scope": "csharp_managed_world",
                "native_api_version": None,
                "scene_host_bridge_version": 4,
                "safe_runtime_references": True,
                "uuid_lookup": "indexed",
                "transform_batch_read_write": True,
                "batch_and_queue_capacity": 4096,
                "editor_shared_update_commit": True,
                "read_visibility": "committed_state",
                "write_conflict_policy": "last_submission_wins",
                "typed_signal_mailboxes": True,
                "signal_delivery": "after_commit_explicit_poll",
                "threading": "world_owner_thread_only",
                "direct_foreign_script_calls": False,
                "writable_native_memory_views": False,
                "generic_component_batches": False,
                "spawn_despawn_commands": False,
            },
        },
        "render_backends": ["Direct3D11", "Vulkan"],
        "render_backend_status": {"Direct3D11": "preview_implemented", "Vulkan": "probe_only"},
        "scene": {
            "authoritative_owner": "C#_Runtime.World",
            "object_api": "GameObject",
            "node_frontend_api": False,
            "native_object_api_version": None,
            "native_plugin_abi_version": 2,
            "gameplay_host_bridge_version": 3,
            "legacy_native_exports": False,
            "format_version": 1,
            "organization": "flat_object_list",
            "parent_child_ownership": False,
            "transform_inheritance": False,
            "file_extension": ".ncmascene",
            "legacy_scene_versions_readable": [],
            "legacy_scene_compatibility": False,
            "atomic_file_save": True,
            "general_component_serialization": True,
            "complete_in_memory_component_snapshots": True,
            "document_project": "managed/Ncma.Scene",
            "document_snapshot_version": 1,
            "world_asset_separation": False,
        },
        "agent_contract": {
            "format": "JSON Schema capabilities",
            "mutation_risks": ["read_only", "reversible", "destructive"],
            "managed_gateway": "C#_Editor.Core_EditSession",
            "managed_contract_version": 2,
            "managed_gateway_implemented": True,
            "managed_gateway_transport_implemented": False,
            "default_permission": "read_only",
            "revision_guards": True,
            "bounded_idempotency_cache": True,
            "destructive_uuid_authorization": True,
            "managed_capabilities": [
                "ncma.capabilities.list", "ncma.engine.component_types", "ncma.scene.inspect",
                "ncma.scene.validate", "ncma.scene.transaction", "ncma.scene.delete_object",
                "ncma.history.undo", "ncma.history.redo",
            ],
            "domains": {
                "scene": "shared_active_editor_commands_no_MCP_transport",
                "animation": "existing_isolated_native_preview_MCP",
                "ui": "model_only_no_editing_gateway",
                "tools": "existing_CLI_inspect_FBX_animation_MCP",
                "engine_extensions": "trusted_managed_component_registration_only",
            },
            "arbitrary_code_execution": False,
            "project_file_mutation_gateway": False,
        },
        "animation": {
            "runtime": "C++ skeletal sampling, root motion, notifies and action preview",
            "native_abi": 1,
            "scene_component": False,
            "model_import": True,
            "model_import_formats": ["FBX"],
            "gpu_skinning": False,
        },
        "mcp": {
            "transport": "stdio",
            "protocol_version": "2025-11-25",
            "entrypoint": "python -m ncma_tools.cli mcp --root <project>",
            "scope": "isolated_animation_preview",
            "live_editor_connection": False,
            "default_permission": "read_only",
            "mutation_opt_in": "--allow-mutations",
            "tool_prefix": "ncma.animation.",
        },
        "paths": {
            "native": str(root / "engine" / "source" / "runtime"),
            "managed": str(root / "managed" / "Ncma.Managed"),
            "python": str(root / "python"),
        },
    }


def write_manifest(root: Path, output: Path) -> None:
    output.write_text(
        json.dumps(inspect_project(root), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
