<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ncma.Scene.Rendering/Ncma.Scene.Rendering.csproj" />
    <ProjectReference Include="../Ncma.Editor.Services/Ncma.Editor.Services.csproj" />
    <ProjectReference Include="../Ncma.Player.App/Ncma.Player.App.csproj" />
  </ItemGroup>
</Project>
