// White-box fault injection is restricted to this test TU; no production fault/debug export.
#include "../../engine/source/plugins/renderer/RendererPlugin.cpp"
#include "../../engine/source/plugins/contracts/NcmaPlatform.h"
#include <iostream>
#include <filesystem>
static void Check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
int main(int argc,char** argv) {
    try{
        if(argc!=2)return 2;
        const auto path=std::filesystem::path(argv[1]);
        HMODULE library=LoadLibraryExW(path.c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);
        Check(library!=nullptr,"Platform load failed.");
        auto get=reinterpret_cast<NcmaGetApiV1>(GetProcAddress(library,"ncma_plugin_get_api"));
        NcmaErrorV1 error{};NcmaPlatformApiV1 platform{};NcmaRendererApiV1 api{};
        Check(get && get(1,0,&platform,sizeof(platform),&error)==0,"Platform API");
        Check(ncma_plugin_get_api(1,0,&api,sizeof(api),&error)==0,"Renderer API");
        NcmaRendererApiV1_1 modern{};
        Check(ncma_plugin_get_api(1,1,&modern,sizeof(modern),&error)==NCMA_OK && modern.base.module.minor==1 && modern.configure_reference,"Renderer 1.1 reference controls");
        NcmaRendererApiV1_2 latest{};
        Check(ncma_plugin_get_api(1,2,&latest,sizeof(latest),&error)==NCMA_OK && latest.base.base.module.minor==2 && latest.query_scene_render,"Renderer 1.2 scene query");
        Check(ncma_plugin_get_api(1,2,&modern,sizeof(modern),&error)==NCMA_BUFFER_TOO_SMALL,"Short renderer 1.2 table");
        Check(ncma_plugin_get_api(1,3,&latest,sizeof(latest),&error)==NCMA_ABI_MISMATCH,"Unknown renderer minor");
        uint64_t platformModule=0,renderModule=0,window=0,handle=0,group=0;
        Check(platform.module.initialize(nullptr,0,&platformModule,&error)==0,"Platform init");
        Check(api.module.initialize(nullptr,0,&renderModule,&error)==0,"Renderer init");
        const uint8_t title[]="Renderer native faults";
        NcmaWindowDescriptionV1 windowDesc{sizeof(windowDesc),256,256,0,title,sizeof(title)-1,0};
        Check(platform.create_window(platformModule,&windowDesc,&window,&error)==0,"Window create");
        NcmaRendererDescriptionV1 desc{sizeof(desc),1,1,0,platformModule,window,256,256,{0,0}};
        Check(api.create_renderer(renderModule,&desc,&handle,&error)==0,"Renderer create");
        NcmaSceneRenderApiV1 scene{};
        Check(latest.query_scene_render(renderModule,6,&scene,sizeof(scene),&error)==NCMA_ABI_MISMATCH,"Unknown scene service version");
        Check(latest.query_scene_render(renderModule,1,&scene,47,&error)==NCMA_BUFFER_TOO_SMALL && error.required_bytes==48,"Short scene service table");
        Check(latest.query_scene_render(renderModule,1,&scene,sizeof(scene),&error)==NCMA_OK && scene.version==1 && scene.capabilities==1,"Scene service negotiation");
        const float vertices[36]{-0.8f,-0.7f,.5f,0,0,1,0,0,1,0,0,1, .6f,-.7f,.5f,0,0,1,1,0,1,0,0,1, -.8f,.7f,.5f,0,0,1,0,1,1,0,0,1};
        uint32_t indices[3]{0,1,2};
        NcmaMeshDescriptionV1 meshDesc{48,1,3,3,144,12,48,0,reinterpret_cast<const uint8_t*>(vertices),indices};
        NcmaGpuMeshV1 mesh{123,456};
        auto badMesh=meshDesc;badMesh.vertex_count=UINT32_MAX;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT && mesh.value==123,"Count overflow rejected without publishing");
        badMesh=meshDesc;badMesh.layout=99;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Unknown mesh layout");
        badMesh=meshDesc;badMesh.vertex_bytes--;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Short vertex buffer");
        badMesh=meshDesc;badMesh.index_bytes--;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Short index buffer");
        badMesh=meshDesc;badMesh.struct_size=47;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Mesh descriptor version/size");
        badMesh=meshDesc;badMesh.reserved=1;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Mesh reserved bits");
        indices[2]=3;
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Index out of bounds");indices[2]=2;
        Check(renderer->backend->GetLiveResourceCount()==0 && renderer->meshes.empty(),"Failed mesh create leaked resources");
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&mesh,&error)==NCMA_OK,"Mesh create");
        uint32_t meshThread=0;
        std::thread meshWorker([&]{NcmaGpuMeshV1 result{};NcmaErrorV1 e{};meshThread=scene.create_mesh(renderModule,handle,&meshDesc,&result,&e);});meshWorker.join();
        Check(meshThread==NCMA_WRONG_THREAD,"Mesh create owner thread");
        auto foreignMesh=mesh;foreignMesh.generation++;
        Check(scene.destroy_mesh(renderModule,handle,foreignMesh,&error)==NCMA_INVALID_HANDLE,"Mesh generation ownership");
        NcmaMeshFrameV1 meshFrame{64,1,1,handle,{0,0,256,256},{0,0,0,1},{0,0}};
        NcmaMeshDrawV1 draw{mesh,0,3,{0,0},{},{1,1,1,1}};
        for(int i=0;i<16;++i)draw.model_view_projection[i]=i%5==0?1.0f:0.0f;
        draw.index_count=6;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_INVALID_ARGUMENT && renderer->stats.submitted_frames==0,"Full validation before GPU");draw.index_count=3;
        draw.reserved[1]=1;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_INVALID_ARGUMENT,"Reserved draw bits");draw.reserved[1]=0;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_OK,"Actual mesh submit");
        Check(scene.destroy_mesh(renderModule,handle,mesh,&error)==NCMA_BUSY,"Active mesh release retained");
        Check(api.present(renderModule,handle,&error)==NCMA_OK,"Mesh present");
        NcmaSceneRenderStatsV1 meshStats{};
        Check(scene.stats(renderModule,handle,&meshStats,&error)==NCMA_OK && meshStats.mesh_creates==1 && meshStats.uploaded_bytes==156 && meshStats.live_meshes==1,"Mesh counters");
        Check(scene.destroy_mesh(renderModule,handle,mesh,&error)==NCMA_OK,"Mesh release after completion");
        Check(scene.destroy_mesh(renderModule,handle,mesh,&error)==NCMA_INVALID_HANDLE,"Stale mesh");
        Check(renderer->backend->GetLiveResourceCount()==0,"Mesh kernel/geometry teardown");
        std::vector<NcmaGpuMeshV1> many(128);
        for(auto& resource:many)Check(scene.create_mesh(renderModule,handle,&meshDesc,&resource,&error)==NCMA_OK,"Mesh budget allocation");
        NcmaGpuMeshV1 refused{};
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&refused,&error)==NCMA_INVALID_ARGUMENT && refused.value==0,"128 mesh budget transactional refusal");
        for(auto resource:many)Check(scene.destroy_mesh(renderModule,handle,resource,&error)==NCMA_OK,"Mesh budget release");
        // Budget arithmetic at the resident limit, without allocating 256MiB in this fault test.
        renderer->meshStats.resident_bytes=256ull*1024*1024;
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&refused,&error)==NCMA_INVALID_ARGUMENT && renderer->meshes.empty(),"Resident byte budget preflight");
        renderer->meshStats.resident_bytes=0;
        Check(renderer->backend->GetLiveResourceCount()==0,"All mesh GPU objects released");
        NcmaSceneRenderApiV2 bind{};
        Check(latest.query_scene_render(renderModule,2,&bind,55,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==56,"Short bind service");
        Check(latest.query_scene_render(renderModule,2,&bind,sizeof(bind),&error)==NCMA_OK&&bind.base.version==2&&bind.base.capabilities==3&&bind.create_bind_pose_mesh,"Bind service negotiation");
        uint8_t skinVertices[240]{};float palette[16]{};for(int i=0;i<16;++i)palette[i]=i%5==0?1.0f:0.0f;
        for(int i=0;i<3;++i){std::memcpy(skinVertices+i*80,vertices+i*12,48);const float weight=1;std::memcpy(skinVertices+i*80+56,&weight,4);}
        NcmaBindPoseMeshDescriptionV2 skin{{64,2,3,3,240,12,80,0,skinVertices,indices},1,64,palette};
        auto badSkin=skin;badSkin.palette_bytes=63;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&badSkin,&refused,&error)==NCMA_INVALID_ARGUMENT&&refused.value==0,"Palette byte preflight");
        badSkin=skin;badSkin.palette_count=4097;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&badSkin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Palette count budget");
        badSkin=skin;badSkin.mesh.vertex_count=UINT32_MAX;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&badSkin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Skin count overflow");
        palette[15]=0;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Nonaffine palette");palette[15]=1;
        palette[0]=std::numeric_limits<float>::quiet_NaN();
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Nonfinite palette");palette[0]=1;
        skinVertices[48]=1;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Active palette joint bound");skinVertices[48]=0;
        const float invalidWeight=-1;std::memcpy(skinVertices+56,&invalidWeight,4);
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Negative weight");const float one=1;std::memcpy(skinVertices+56,&one,4);
        skinVertices[72]=1;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Nonzero skin padding");skinVertices[72]=0;
        badMesh=skin.mesh;badMesh.struct_size=48;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&refused,&error)==NCMA_INVALID_ARGUMENT,"Static v1 cannot silently accept skin layout");
        Check(refused.value==0&&renderer->meshes.empty()&&renderer->backend->GetLiveResourceCount()==0,"Bind negatives published/leaked resources");
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_OK,"Bind mesh create");
        Check(renderer->meshes.at(refused.value)->vertexStride==80&&renderer->meshStats.resident_bytes==252,"Bind mesh resident stride/bytes");
        Check(scene.destroy_mesh(renderModule,handle,refused,&error)==NCMA_OK&&renderer->backend->GetLiveResourceCount()==0,"Bind mesh drain via v1 lease");
        NcmaResourceRenderApiV3 typed{};
        Check(latest.query_scene_render(renderModule,3,&typed,71,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==72,"Short resource service");
        Check(latest.query_scene_render(renderModule,3,&typed,sizeof(typed),&error)==NCMA_OK&&typed.version==3&&typed.capabilities==0x3c,"Resource service negotiation");
        uint8_t rgba[4]{128,64,32,255};NcmaTextureMipV3 mip{1,1,0,4};
        NcmaTextureDescriptionV3 textureDesc{48,1,1,2,1,4,{0,0},&mip,rgba};NcmaGpuResourceV3 texture{123,456},material{},target{};
        auto invalidTexture=textureDesc;invalidTexture.width=4097;
        Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT&&texture.value==123,"Texture dimension candidate unpublished");
        invalidTexture=textureDesc;invalidTexture.format=99;Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT,"Unknown texture format");
        mip.row_pitch=3;Check(typed.create_texture(renderModule,handle,&textureDesc,&texture,&error)==NCMA_INVALID_ARGUMENT,"Texture stride");mip.row_pitch=4;
        invalidTexture=textureDesc;invalidTexture.data_bytes=5;Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT,"Trailing texture bytes");
        invalidTexture=textureDesc;invalidTexture.width=2;Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT,"Incomplete/overbudget mip");
        const auto resourceCount=renderer->backend->GetLiveResourceCount();
        Check(typed.create_texture(renderModule,handle,&textureDesc,&texture,&error)==NCMA_OK,"Texture initial upload");
        NcmaMaterialDescriptionV3 materialDesc{};materialDesc.struct_size=160;for(float& x:materialDesc.base_color)x=1;materialDesc.surface[1]=.5f;materialDesc.surface[2]=1;materialDesc.surface[3]=.5f;materialDesc.textures[0]=texture;
        materialDesc.textures[1]=texture;Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_INVALID_ARGUMENT&&material.value==0,"sRGB normal role rejected");materialDesc.textures[1]={};
        materialDesc.channels[0]=4;Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_INVALID_ARGUMENT,"Invalid material channel");materialDesc.channels[0]=0;
        materialDesc.textures[0].generation++;Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_INVALID_HANDLE,"Foreign texture generation");materialDesc.textures[0]=texture;
        Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_OK,"Lazy material shader create");
        Check(typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_BUSY,"Material pins texture");
        NcmaTargetDescriptionV3 targetDesc{16,256,256,0};auto badTarget=targetDesc;badTarget.width=UINT32_MAX;Check(typed.create_target(renderModule,handle,&badTarget,&target,&error)==NCMA_INVALID_ARGUMENT,"Target integer overflow preflight");
        Check(typed.create_target(renderModule,handle,&targetDesc,&target,&error)==NCMA_OK,"Target create");
        ID3D11ShaderResourceView* imageView=nullptr;
        Check(ncma_renderer_gui_image_v1(renderModule,handle,texture,0,0,&imageView,&error)==NCMA_INVALID_HANDLE,"GUI accepts target tokens only");
        auto foreignTarget=target;foreignTarget.generation++;
        Check(ncma_renderer_gui_image_v1(renderModule,handle,foreignTarget,0,0,&imageView,&error)==NCMA_INVALID_HANDLE,"GUI image foreign generation");
        Check(ncma_renderer_gui_image_v1(renderModule,handle,target,1,0,&imageView,&error)==NCMA_BUSY,"Unsubmitted target cannot masquerade as current image");
        for(int i=0;i<64;i++)Check(ncma_renderer_gui_image_v1(renderModule,handle,target,0,1,&imageView,&error)==NCMA_OK&&imageView,"Bounded GUI image pin");
        Check(ncma_renderer_gui_image_v1(renderModule,handle,target,0,1,&imageView,&error)==NCMA_BUSY,"GUI pin overflow");
        Check(typed.destroy_resource(renderModule,handle,target,&error)==NCMA_BUSY,"CPU GUI data pins target before GPU submit");
        for(int i=0;i<64;i++)Check(ncma_renderer_release_gui_image_v1(renderModule,handle,target,&error)==NCMA_OK,"GUI image unpin");
        Check(ncma_renderer_release_gui_image_v1(renderModule,handle,target,&error)==NCMA_INVALID_HANDLE,"GUI image double unpin");
        NcmaGpuMeshV1 typedMesh{};Check(scene.create_mesh(renderModule,handle,&meshDesc,&typedMesh,&error)==NCMA_OK,"Typed negative mesh");
        NcmaResourceDrawV3 resourceDraw{};resourceDraw.mesh=typedMesh;resourceDraw.material=material;resourceDraw.index_count=3;
        for(int i=0;i<16;++i)resourceDraw.model[i]=resourceDraw.model_view_projection[i]=resourceDraw.normal_matrix[i]=i%5==0?1.f:0.f;
        NcmaResourceFrameV3 resourceFrame{};resourceFrame.struct_size=136;resourceFrame.draw_count=1;resourceFrame.frame=2;resourceFrame.generation=handle;resourceFrame.target=target;resourceFrame.viewport[2]=resourceFrame.viewport[3]=256;resourceFrame.clear[3]=1;resourceFrame.camera[2]=2;resourceFrame.light_direction[2]=1;resourceFrame.exposure=1;resourceFrame.ambient=.03f;
        resourceDraw.model[15]=0;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_ARGUMENT,"Nonaffine typed draw");resourceDraw.model[15]=1;
        resourceDraw.normal_matrix[0]=2;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_ARGUMENT,"Inconsistent inverse-transpose");resourceDraw.normal_matrix[0]=1;
        resourceDraw.material=texture;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_HANDLE,"Wrong type resource draw");resourceDraw.material=material;
        resourceFrame.draw_count=4097;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_ARGUMENT,"Typed batch budget");resourceFrame.draw_count=1;
        Check(renderer->lastFrame==1&&!renderer->active&&renderer->resourceStats.draws==0,"Rejected typed batch advanced frame");
        NcmaScenePipelineApiV4 pipelineApi{};
        Check(latest.query_scene_render(renderModule,4,&pipelineApi,47,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==48,"Short scene pipeline service");
        Check(latest.query_scene_render(renderModule,4,&pipelineApi,48,&error)==NCMA_OK&&pipelineApi.version==4&&pipelineApi.capabilities==7,"Scene pipeline negotiation");
        NcmaScenePipelineDescriptionV4 description{16,256,256,512};NcmaGpuResourceV3 pipelineKey{123,456};auto invalidDescription=description;invalidDescription.shadow_resolution=300;
        const auto pipelineResourceCount=renderer->backend->GetLiveResourceCount();
        Check(pipelineApi.create(renderModule,handle,&invalidDescription,&pipelineKey,&error)==NCMA_INVALID_ARGUMENT&&pipelineKey.value==123,"Invalid shadow candidate unpublished");
        invalidDescription=description;invalidDescription.width=UINT32_MAX;
        Check(pipelineApi.create(renderModule,handle,&invalidDescription,&pipelineKey,&error)==NCMA_INVALID_ARGUMENT,"Scene dimensions overflow");
        Check(pipelineApi.create(renderModule,handle,&description,&pipelineKey,&error)==NCMA_OK,"Actual scene shaders/resources create");
        NcmaSceneFrameV4 sf{};sf.base=resourceFrame;sf.base.struct_size=240;sf.base.camera[3]=1;sf.pipeline=pipelineKey;sf.pass_count=3;
        for(int i=0;i<16;++i)sf.light_view_projection[i]=i%5==0?1.f:0.f;sf.shadow[3]=3;
        NcmaSceneDrawV4 batch[2]{{resourceDraw,{0,.5f,0,0}},{resourceDraw,{0,.5f,0,0}}};
        NcmaScenePassV4 scenePasses[3]{{6,{}},{7,{.03f,0,0}},{8,{1,0,0}}};
        sf.base.draw_count=2;batch[1].draw.reserved[0]=1;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Last invalid scene draw preflight");batch[1].draw.reserved[0]=0;
        sf.caster_count=2;batch[1].override_surface[2]=2;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,batch,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Last invalid caster/scalar preflight");batch[1].override_surface[2]=0;
        sf.caster_count=0;sf.base.draw_count=4097;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene bounded geometry batch");sf.base.draw_count=2;
        sf.caster_count=4097;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,batch,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene bounded shadow batch");sf.caster_count=0;
        sf.pipeline.generation++;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene foreign pipeline generation");sf.pipeline=pipelineKey;
        sf.light_view_projection[0]=std::numeric_limits<float>::quiet_NaN();
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene nonfinite light matrix");sf.light_view_projection[0]=1;
        scenePasses[0].operation=8;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene tone before geometry rejected");scenePasses[0].operation=6;
        scenePasses[2].parameters[0]=0;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene invalid exposure");scenePasses[2].parameters[0]=1;
        NcmaScenePipelineStatsV4 ss{};
        Check(pipelineApi.stats(renderModule,handle,&ss,&error)==NCMA_OK&&ss.pipelines==1&&ss.geometry_draws==0&&ss.shadow_draws==0&&renderer->lastFrame==1&&!renderer->active,"Rejected scene has no partial execution");
        uint32_t sceneWrongThread=0;
        std::thread sceneWorker([&]{NcmaScenePipelineStatsV4 stats{};NcmaErrorV1 e{};sceneWrongThread=pipelineApi.stats(renderModule,handle,&stats,&e);});sceneWorker.join();
        Check(sceneWrongThread==NCMA_WRONG_THREAD,"Scene owner thread required");
        auto foreignPipeline=pipelineKey;foreignPipeline.generation++;
        Check(pipelineApi.destroy(renderModule,handle,foreignPipeline,&error)==NCMA_INVALID_HANDLE,"Foreign pipeline release");
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_OK,"Valid scene batch executes after all negative cases");
        Check(pipelineApi.destroy(renderModule,handle,pipelineKey,&error)==NCMA_BUSY,"Active scene group retained");
        Check(api.present(renderModule,handle,&error)==NCMA_OK,"Actual scene present");
        Check(pipelineApi.destroy(renderModule,handle,pipelineKey,&error)==NCMA_OK&&renderer->backend->GetLiveResourceCount()==pipelineResourceCount,"Scene group fully drained");
        Check(pipelineApi.destroy(renderModule,handle,pipelineKey,&error)==NCMA_INVALID_HANDLE,"Released scene pipeline");
        Check(scene.destroy_mesh(renderModule,handle,typedMesh,&error)==NCMA_OK,"Typed negative mesh drain");
        Check(typed.capture_target(renderModule,handle,target,nullptr,0,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==256*256*4,"Target readback short capacity");
        renderer->resourceStats.resident_bytes=256ull*1024*1024;
        NcmaGpuResourceV3 denied{};Check(typed.create_texture(renderModule,handle,&textureDesc,&denied,&error)==NCMA_INVALID_ARGUMENT&&denied.value==0,"Resident texture budget");renderer->resourceStats.resident_bytes=4+256*256*8;
        Check(typed.destroy_resource(renderModule,handle,target,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,material,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_OK,"Typed dependency drain");
        Check(typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_INVALID_HANDLE,"Released resource");
        Check(renderer->resourceStats.resident_bytes==0&&renderer->backend->GetLiveResourceCount()==resourceCount,"Resource candidate/fallback GPU leak");
        NcmaSkinApiV5 skinApi{};
        Check(latest.query_scene_render(renderModule,5,&skinApi,55,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==56,"Short skin API");
        Check(latest.query_scene_render(renderModule,5,&skinApi,56,&error)==NCMA_OK&&skinApi.version==5&&skinApi.capabilities==3,"Skin API negotiation");
        std::array<uint8_t,240> gpuSkinVertices{};
        for(int i=0;i<3;i++){std::memcpy(gpuSkinVertices.data()+i*80,vertices+i*12,48);float weight=1;std::memcpy(gpuSkinVertices.data()+i*80+64,&weight,4);}
        NcmaSkinMeshV5 skinDesc{{56,3,3,3,240,12,80,0,gpuSkinVertices.data(),indices},1,0};NcmaGpuMeshV1 skinMesh{123,456};
        auto badGpuSkin=skinDesc;badGpuSkin.binding_count=0;Check(skinApi.create(renderModule,handle,&badGpuSkin,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Skin create candidate rejected");
        badGpuSkin.binding_count=1025;Check(skinApi.create(renderModule,handle,&badGpuSkin,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Skin binding budget rejected");
        float zeroWeight=0;std::memcpy(gpuSkinVertices.data()+64,&zeroWeight,4);
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Zero influence sum rejected");
        float negativeWeight=-1;std::memcpy(gpuSkinVertices.data()+64,&negativeWeight,4);
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Negative influence rejected");
        float validWeight=1;std::memcpy(gpuSkinVertices.data()+64,&validWeight,4);uint32_t badJoint=1;std::memcpy(gpuSkinVertices.data()+48,&badJoint,4);
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Mesh-local joint range rejected");
        badJoint=0;std::memcpy(gpuSkinVertices.data()+48,&badJoint,4);
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_OK,"Actual compute skin source/output create");
        NcmaMeshDescriptionV1 mixedStaticDesc{48,1,3,3,144,12,48,0,reinterpret_cast<const uint8_t*>(vertices),indices};NcmaGpuMeshV1 mixedStatic{};
        Check(scene.create_mesh(renderModule,handle,&mixedStaticDesc,&mixedStatic,&error)==NCMA_OK,"Mixed static/skin source");
        Check(scene.destroy_mesh(renderModule,handle,mixedStatic,&error)==NCMA_OK,"Static released before last skin");
        NcmaSkinPaletteV5 gpuPalette{};for(int i=0;i<16;i++)gpuPalette.model[i]=gpuPalette.normal[i]=i%5==0?1.f:0.f;gpuPalette.model[12]=.25f;
        NcmaSkinRequestV5 skinJobs[2]{{skinMesh,0,1},{skinMesh,1,1}};NcmaSkinPaletteV5 pair[2]{gpuPalette,gpuPalette};NcmaSkinBatchV5 skinBatch{32,2,3,handle,2,0};NcmaSkinStatsV5 skinStatus{};
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,pair,&error)==NCMA_INVALID_ARGUMENT,"Duplicate GPU skin output preflight");
        skinBatch.request_count=1;skinBatch.palette_count=1;gpuPalette.normal[0]=2;
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_INVALID_ARGUMENT,"Skin normal inverse-transpose preflight");gpuPalette.normal[0]=1;
        auto foreignSkin=skinMesh;foreignSkin.generation++;skinJobs[0].mesh=foreignSkin;
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_INVALID_HANDLE,"Foreign skin renderer generation");skinJobs[0].mesh=skinMesh;
        Check(skinApi.stats(renderModule,handle,&skinStatus,&error)==NCMA_OK&&skinStatus.batches==0&&renderer->skins.at(skinMesh.value)->frame==0,"Rejected skin did not dispatch/publish");
        uint32_t skinWrongThread=0;std::thread skinThread([&]{NcmaSkinStatsV5 s{};NcmaErrorV1 e{};skinWrongThread=skinApi.stats(renderModule,handle,&s,&e);});skinThread.join();Check(skinWrongThread==NCMA_WRONG_THREAD,"Skin owner thread");
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_OK,"GPU skin dispatch");
        std::array<float,36> skinResult{};Check(skinApi.capture(renderModule,handle,skinMesh,reinterpret_cast<uint8_t*>(skinResult.data()),144,&error)==NCMA_OK,"GPU skin numerical readback");
        for(int i=0;i<3;i++){Check(std::abs(skinResult[static_cast<size_t>(i)*12]-vertices[i*12]-.25f)<1e-5f,"GPU skin position oracle");Check(std::abs(skinResult[static_cast<size_t>(i)*12+5]-1)<1e-5f,"GPU skin normal oracle");}
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_INVALID_ARGUMENT,"Repeated pose frame rejected");
        Check(scene.destroy_mesh(renderModule,handle,skinMesh,&error)==NCMA_INVALID_ARGUMENT,"Skin is not an old static release type");
        Check(skinApi.destroy(renderModule,handle,skinMesh,&error)==NCMA_OK&&skinApi.stats(renderModule,handle,&skinStatus,&error)==NCMA_OK&&skinStatus.meshes==0&&skinStatus.resident_bytes==0,"Skin ring/source/output fully drained");
        Check(skinApi.destroy(renderModule,handle,skinMesh,&error)==NCMA_INVALID_HANDLE,"Released GPU skin handle");
        Check(renderer->backend->GetLiveResourceCount()==resourceCount,"Skin RHI resources leaked");
        uint32_t foreign=0;
        std::thread thread([&]{NcmaRendererStatsV1 status{};NcmaErrorV1 threadError{};foreign=api.stats(renderModule,handle,&status,&threadError);});thread.join();
        Check(foreign==NCMA_WRONG_THREAD,"Wrong thread rejected");
        Rhi::GraphicsPipelineDescription shader{};
        shader.VertexShaderSource="syntax_error";shader.PixelShaderSource="syntax_error";
        shader.VertexLayout.push_back({"POSITION",0,Rhi::VertexFormat::Float3,0});
        std::string diagnostic;
        Check(!renderer->backend->CreateGraphicsPipeline(shader,diagnostic),"Invalid shader unexpectedly compiled.");
        Check(!diagnostic.empty(),"Shader compilation diagnostic missing.");
        // Remove intentionally generated compile diagnostic from validation before successful draw.
        renderer->validation->ClearStoredMessages();
        Check(api.create_resources(renderModule,handle,&group,&error)==0,"Reference resource create");
        NcmaRenderFrameV1 frame{sizeof(frame),3,3,{},{0,0,256,256},1,.35F,.28F,0};
        for(int i=0;i<16;++i)frame.model[i]=i%5==0?1.0F:0.0F;
        NcmaRenderPassV1 passes[3]{{1,1,group,{}},{2,1,group,{}},{3,2,group,{}}};
        auto invalid=frame;invalid.pass_count=65;
        Check(api.submit(renderModule,handle,&invalid,passes,&error)==NCMA_INVALID_ARGUMENT,"Pass budget");
        passes[0].resources=handle;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_INVALID_HANDLE,"Wrong type handle");
        passes[0].resources=group;passes[2].shader_contract=1;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_INVALID_ARGUMENT,"Shader contract");
        passes[2].shader_contract=2;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==0,"Submit");
        Check(api.destroy_resources(renderModule,handle,group,&error)==NCMA_BUSY,"Active frame retained");
        Check(api.present(renderModule,handle,&error)==0,"Present");
        Check(api.wait_idle(renderModule,handle,&error)==0,"Wait GPU");
        NcmaGpuMeshV1 faultMesh{};
        Check(typed.create_texture(renderModule,handle,&textureDesc,&texture,&error)==NCMA_OK,"Fault texture create");materialDesc.textures[0]=texture;
        Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_OK&&typed.create_target(renderModule,handle,&targetDesc,&target,&error)==NCMA_OK,"Fault material/target create");
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&faultMesh,&error)==NCMA_OK,"Active fault mesh create");
        draw.mesh=faultMesh;meshFrame.frame=4;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_OK,"Active fault mesh submit");
        Check(Failure(&error,"Injected post-submit capture failure.")==NCMA_INTERNAL_ERROR,"Capture execution fault fail-stop");
        Check(!renderer->active && !renderer->measuring,"Faulted active frame/query did not abort");
        Check(api.present(renderModule,handle,&error)==NCMA_INTERNAL_ERROR,"Faulted frame cannot present");
        Check(scene.destroy_mesh(renderModule,handle,faultMesh,&error)==NCMA_OK && renderer->meshes.empty(),"Faulted active mesh can drain");
        Check(typed.create_texture(renderModule,handle,&textureDesc,&denied,&error)==NCMA_INTERNAL_ERROR,"Fault texture creation blocked");
        Check(typed.destroy_resource(renderModule,handle,target,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,material,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_OK,"Faulted typed resources drain");
        try {ExecutionScope scope;throw std::runtime_error("Injected post-validation execution failure.");}catch(const std::runtime_error&){}
        frame.frame=5;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_INTERNAL_ERROR,"Execution exception fail-stop");
        renderer->failed=true;renderer->faultResult=NCMA_DEVICE_LOST;renderer->stats.state=2; // Device-lost state machine injection, not a driver reset.
        frame.frame=5;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_DEVICE_LOST,"Lost submit fail-stop");
        Check(api.present(renderModule,handle,&error)==NCMA_DEVICE_LOST,"Lost present fail-stop");
        Check(api.resize(renderModule,handle,300,300,&error)==NCMA_DEVICE_LOST,"Lost resize fail-stop");
        meshFrame.frame=5;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_DEVICE_LOST,"Lost static batch fail-stop");
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&refused,&error)==NCMA_DEVICE_LOST,"Lost mesh create fail-stop");
        Check(pipelineApi.create(renderModule,handle,&description,&pipelineKey,&error)==NCMA_DEVICE_LOST,"Lost scene create fail-stop");
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_DEVICE_LOST,"Lost scene submit fail-stop");
        Check(api.destroy_resources(renderModule,handle,group,&error)==0,"Faulted release");
        Check(api.destroy_resources(renderModule,handle,group,&error)==NCMA_INVALID_HANDLE,"Stale group");
        Check(renderer->backend->GetLiveResourceCount()==0,"Native GPU resource maps leaked.");
        Check(api.destroy_renderer(renderModule,handle,&error)==0,"Destroy");
        Check(api.stats(renderModule,handle,nullptr,&error)==NCMA_INVALID_HANDLE,"Stale renderer");
        Check(api.module.shutdown(renderModule,&error)==0,"Renderer shutdown");
        Check(platform.destroy_window(platformModule,window,&error)==0,"Window destroy");
        Check(platform.module.shutdown(platformModule,&error)==0,"Platform shutdown");
        FreeLibrary(library);
        std::cout<<"Native render ABI bounds/thread/shader rejection and injected fault state passed; no real device reset performed.\n";return 0;
    }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}
}
