// White-box fault injection is restricted to this test TU; no production fault/debug export.
#define NCMA_RENDERER_TEST_WAIT
#include "../../engine/source/plugins/renderer/RendererPlugin.cpp"
#include "../../engine/source/plugins/contracts/NcmaPlatform.h"
#include <iostream>
#include <filesystem>
static void Check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
int main(int argc,char** argv) {
    try{
        if(argc!=2)return 2;
        const auto path=std::filesystem::path(argv[1]);
        HMODULE library=LoadLibraryExW(path.c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);
        Check(library!=nullptr,"Platform load failed.");
        auto get=reinterpret_cast<NcmaGetApiV1>(GetProcAddress(library,"ncma_plugin_get_api"));
        NcmaErrorV1 error{};NcmaPlatformApiV1 platform{};NcmaRendererApiV1 api{};
        Check(get && get(1,0,&platform,sizeof(platform),&error)==0,"Platform API");
        Check(ncma_plugin_get_api(1,0,&api,sizeof(api),&error)==0,"Renderer API");
        NcmaRendererApiV1_1 modern{};
        Check(ncma_plugin_get_api(1,1,&modern,sizeof(modern),&error)==NCMA_OK && modern.base.module.minor==1 && modern.configure_reference,"Renderer 1.1 reference controls");
        NcmaRendererApiV1_2 latest{};
        Check(ncma_plugin_get_api(1,2,&latest,sizeof(latest),&error)==NCMA_OK && latest.base.base.module.minor==2 && latest.query_scene_render,"Renderer 1.2 scene query");
        Check(ncma_plugin_get_api(1,2,&modern,sizeof(modern),&error)==NCMA_BUFFER_TOO_SMALL,"Short renderer 1.2 table");
        Check(ncma_plugin_get_api(1,3,&latest,sizeof(latest),&error)==NCMA_ABI_MISMATCH,"Unknown renderer minor");
        uint64_t platformModule=0,renderModule=0,window=0,handle=0,group=0;
        Check(platform.module.initialize(nullptr,0,&platformModule,&error)==0,"Platform init");
        Check(api.module.initialize(nullptr,0,&renderModule,&error)==0,"Renderer init");
        const uint8_t title[]="Renderer native faults";
        NcmaWindowDescriptionV1 windowDesc{sizeof(windowDesc),256,256,0,title,sizeof(title)-1,0};
        Check(platform.create_window(platformModule,&windowDesc,&window,&error)==0,"Window create");
        NcmaRendererDescriptionV1 desc{sizeof(desc),1,1,0,platformModule,window,256,256,{0,0}};
        Check(api.create_renderer(renderModule,&desc,&handle,&error)==0,"Renderer create");
        NcmaSceneRenderApiV1 scene{};
        NcmaUiTargetApiV1 uiTargets{};
        Check(latest.query_scene_render(renderModule,7,&uiTargets,sizeof(uiTargets)-1,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==72,"Short UI target API");
        Check(latest.query_scene_render(renderModule,7,&uiTargets,sizeof(uiTargets),&error)==NCMA_OK&&uiTargets.version==1&&uiTargets.capabilities==7,"UI target API negotiation");
        Check(latest.query_scene_render(renderModule,11,&scene,sizeof(scene),&error)==NCMA_ABI_MISMATCH,"Unknown scene service version");
        NcmaShaderApiV1 shaders{};
        Check(latest.query_scene_render(renderModule,8,&shaders,31,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==32,"Short shader API");
        Check(latest.query_scene_render(renderModule,8,&shaders,32,&error)==NCMA_OK&&shaders.version==1&&shaders.capabilities==1&&shaders.compile&&shaders.validate_preparation,"Shader query8 actual API");
        // Policy-unit boundary only, NOT a claim that real D3DCompile returned a large blob.
        Check(ShaderCompilation::DiagnosticFailure(16384,&error)==NCMA_INVALID_ARGUMENT&&error.reserved==0&&error.required_bytes==16384,"Diagnostic exact budget policy");
        Check(ShaderCompilation::DiagnosticFailure(16385,&error)==NCMA_INVALID_ARGUMENT&&error.reserved==1&&error.required_bytes==16385&&error.message_length<128,"Diagnostic over-budget redacted policy");
        const std::string shaderSource="float4 VSMain(float3 p:POSITION):SV_POSITION{return float4(p,1);}";
        const char* shaderEntry="VSMain";
        NcmaShaderCompileV1 shaderRequest{56,1,0,static_cast<uint32_t>(shaderSource.size()),6,0,0,0,reinterpret_cast<const uint8_t*>(shaderSource.data()),shaderEntry,nullptr};
        NcmaShaderOutputV1 shaderOutput{};std::array<NcmaShaderRowV1,256> shaderRows{};std::vector<uint8_t> shaderBytes(1048576);
        const auto compile=[&](uint32_t rowCapacity=256,uint32_t byteCapacity=1048576){return shaders.compile(renderModule,handle,&shaderRequest,&shaderOutput,shaderRows.data(),rowCapacity,shaderBytes.data(),byteCapacity,&error);};
        Check(compile()==NCMA_OK&&shaderOutput.version==1&&shaderOutput.row_count==1&&shaderRows[0].columns==3&&shaderRows[0].scalar==0&&shaderOutput.bytecode_bytes>4,"Actual shader compile/input reflection");
        const auto savedOutput=shaderOutput;const auto savedRows=shaderRows;const auto savedBytes=shaderBytes;
        Check(compile(0)==NCMA_BUFFER_TOO_SMALL&&std::memcmp(&shaderOutput,&savedOutput,32)==0&&std::memcmp(shaderRows.data(),savedRows.data(),sizeof(shaderRows))==0&&shaderBytes==savedBytes,"Short reflection output atomic");
        Check(compile(256,1)==NCMA_BUFFER_TOO_SMALL&&shaderBytes==savedBytes,"Short bytecode output atomic");
        // A valid first member followed by an unsupported nested struct: no partial publication.
        const std::string lateFailure="struct Nested{float4 Value;};cbuffer C:register(b0){float4 Good;Nested Bad;};float4 VSMain(float3 p:POSITION):SV_POSITION{return float4(p,1)+Good+Bad.Value;}";
        const auto originalRequest=shaderRequest;shaderRequest.source=reinterpret_cast<const uint8_t*>(lateFailure.data());shaderRequest.source_bytes=static_cast<uint32_t>(lateFailure.size());
        Check(compile()==NCMA_UNSUPPORTED_FEATURE&&std::memcmp(&shaderOutput,&savedOutput,32)==0&&std::memcmp(shaderRows.data(),savedRows.data(),sizeof(shaderRows))==0&&shaderBytes==savedBytes,"Unsupported late member atomic");shaderRequest=originalRequest;
        shaderRequest.version=2;Check(compile()==NCMA_ABI_MISMATCH&&shaderBytes==savedBytes,"Wrong shader contract version");shaderRequest.version=1;
        shaderRequest.stage=99;Check(compile()==NCMA_INVALID_ARGUMENT,"Invalid shader stage");shaderRequest.stage=0;
        uint32_t shaderThread=0;std::thread shaderWorker([&]{NcmaErrorV1 e{};shaderThread=shaders.validate_preparation(renderModule,handle,&e);});shaderWorker.join();Check(shaderThread==NCMA_WRONG_THREAD,"Shader owner thread");
        Check(shaders.validate_preparation(renderModule,handle+1,&error)==NCMA_INVALID_HANDLE,"Shader stale renderer");
        renderer->active=true;Check(compile()==NCMA_BUSY&&shaders.validate_preparation(renderModule,handle,&error)==NCMA_BUSY,"Shader active frame blocked including cache boundary");renderer->active=false;
        renderer->failed=true;Check(compile()==NCMA_INTERNAL_ERROR,"Shader fail-stop renderer blocked");renderer->failed=false;
        Check(renderer->backend->GetLiveResourceCount()==0&&renderer->stats.submitted_frames==0,"Shader compilation allocates no GPU pipelines or frames");
        { NcmaShaderPipelineApiV1 registered{};
        Check(latest.query_scene_render(renderModule,9,&registered,39,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==40,"Short registered Shader API");
        Check(latest.query_scene_render(renderModule,9,&registered,40,&error)==NCMA_OK&&registered.version==1&&registered.capabilities==1&&registered.copy_tone_source&&registered.create_scene&&registered.replace_tone,"Registered Tone query9 negotiation");
        std::vector<uint8_t> toneSource(262144,0x77);uint32_t toneSourceBytes=0x1234;
        Check(registered.copy_tone_source(renderModule,handle,toneSource.data(),1,&toneSourceBytes,&error)==NCMA_BUFFER_TOO_SMALL&&toneSourceBytes==0x1234&&toneSource[0]==0x77,"Source short buffer atomic");
        Check(registered.copy_tone_source(renderModule,handle,toneSource.data(),262144,&toneSourceBytes,&error)==NCMA_OK&&toneSourceBytes>100,"Copied exact trusted source");
        shaderRequest.source=toneSource.data();shaderRequest.source_bytes=toneSourceBytes;shaderRequest.entry="VSTone";shaderRequest.entry_bytes=6;
        Check(compile()==NCMA_OK,"Default Tone actual VS reflection");std::vector<uint8_t> toneVertex(shaderBytes.begin(),shaderBytes.begin()+shaderOutput.bytecode_bytes);
        shaderRequest.stage=1;shaderRequest.entry="PSTone";Check(compile()==NCMA_OK,"Default Tone actual PS reflection");std::vector<uint8_t> tonePixel(shaderBytes.begin(),shaderBytes.begin()+shaderOutput.bytecode_bytes);
        NcmaShaderPairV1 pair{32,1,static_cast<uint32_t>(toneVertex.size()),static_cast<uint32_t>(tonePixel.size()),toneVertex.data(),tonePixel.data()};
        NcmaScenePipelineDescriptionV4 registeredDesc{16,256,256,0};NcmaGpuResourceV3 registeredKey{123,456};
        auto badPair=pair;badPair.version=2;
        Check(registered.create_scene(renderModule,handle,&registeredDesc,&badPair,&registeredKey,&error)==NCMA_ABI_MISMATCH&&registeredKey.value==123&&renderer->backend->GetLiveResourceCount()==0,"Wrong program version unpublished");
        badPair=pair;badPair.pixel=toneVertex.data();badPair.pixel_bytes=static_cast<uint32_t>(toneVertex.size());
        Check(registered.create_scene(renderModule,handle,&registeredDesc,&badPair,&registeredKey,&error)==NCMA_INVALID_ARGUMENT&&registeredKey.value==123&&renderer->backend->GetLiveResourceCount()==0,"Wrong actual shader stage before GPU");
        std::string badMemberSource(reinterpret_cast<const char*>(toneSource.data()),toneSourceBytes);Check(badMemberSource.find("ShadowParameters;")!=std::string::npos,"Last member fixture");
        for(size_t at=0;(at=badMemberSource.find("ShadowParameters",at))!=std::string::npos;at+=16)badMemberSource.replace(at,16,"ForgedLastMember");
        shaderRequest.source=reinterpret_cast<const uint8_t*>(badMemberSource.data());shaderRequest.source_bytes=static_cast<uint32_t>(badMemberSource.size());
        Check(compile()==NCMA_OK,"Individually valid PS with forged last constant member");std::vector<uint8_t> forgedPixel(shaderBytes.begin(),shaderBytes.begin()+shaderOutput.bytecode_bytes);
        badPair=pair;badPair.pixel=forgedPixel.data();badPair.pixel_bytes=static_cast<uint32_t>(forgedPixel.size());
        Check(registered.create_scene(renderModule,handle,&registeredDesc,&badPair,&registeredKey,&error)==NCMA_INVALID_ARGUMENT&&registeredKey.value==123&&renderer->backend->GetLiveResourceCount()==0,"Actual last member rejected before GPU/output publication");
        testTonePreparationThrow=true;Check(registered.create_scene(renderModule,handle,&registeredDesc,&pair,&registeredKey,&error)==NCMA_INTERNAL_ERROR&&registeredKey.value==123&&renderer->scenePipelines.empty()&&renderer->sceneStats.creates==0&&renderer->backend->GetLiveResourceCount()==0&&!renderer->failed,"Diagnostic exception before scene publication retains all outputs/counters and cleans candidate");testTonePreparationThrow=false;
        Check(registered.create_scene(renderModule,handle,&registeredDesc,&pair,&registeredKey,&error)==NCMA_OK,"Actual precompiled Tone scene create");
        const auto toneResourceCount=renderer->backend->GetLiveResourceCount();
        testTonePreparationThrow=true;Check(registered.replace_tone(renderModule,handle,registeredKey,&pair,&error)==NCMA_INTERNAL_ERROR&&renderer->backend->GetLiveResourceCount()==toneResourceCount&&renderer->scenePipelines.contains(registeredKey.value)&&!renderer->failed,"Diagnostic exception before Tone exchange retains old stage and releases candidate");testTonePreparationThrow=false;
        testWaitTimeout=true;Check(registered.replace_tone(renderModule,handle,registeredKey,&pair,&error)==NCMA_SHUTDOWN_TIMEOUT&&renderer->backend->GetLiveResourceCount()==toneResourceCount&&renderer->scenePipelines.contains(registeredKey.value),"Tone drain failure retains old stage and retires candidate");testWaitTimeout=false;
        Check(registered.replace_tone(renderModule,handle,registeredKey,&pair,&error)==NCMA_OK&&renderer->backend->GetLiveResourceCount()==toneResourceCount,"Tone atomic replacement resource baseline");
        Check(DestroyScenePipeline(renderModule,handle,registeredKey,&error)==NCMA_OK&&renderer->backend->GetLiveResourceCount()==0,"Registered Tone drain complete");shaderRequest=originalRequest; }
        {NcmaShaderStagesApiV1 stages{};
         Check(latest.query_scene_render(renderModule,10,&stages,55,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==56,"Short registered stages table");
         Check(latest.query_scene_render(renderModule,10,&stages,56,&error)==NCMA_OK&&stages.version==1&&stages.capabilities==3&&stages.copy_source&&stages.create_scene&&stages.replace_scene&&stages.create_skin&&stages.replace_skin,"Registered stages query10/API1");
         uint8_t unchanged=0x77;uint32_t required=123;Check(stages.copy_source(renderModule,handle,1,&unchanged,1,&required,&error)==NCMA_BUFFER_TOO_SMALL&&required==123&&unchanged==0x77,"Skin source short output atomic");
         Check(stages.copy_source(renderModule,handle,2,&unchanged,1,&required,&error)==NCMA_INVALID_ARGUMENT,"Unknown source kind");
         auto code=[&](std::string_view source,const char* entry,uint32_t stage){NcmaShaderCompileV1 request=originalRequest;request.source=reinterpret_cast<const uint8_t*>(source.data());request.source_bytes=static_cast<uint32_t>(source.size());request.entry=entry;request.entry_bytes=static_cast<uint32_t>(std::strlen(entry));request.stage=stage;
          NcmaShaderOutputV1 result{};std::array<NcmaShaderRowV1,256> rows{};std::vector<uint8_t> bytes(1048576);Check(shaders.compile(renderModule,handle,&request,&result,rows.data(),256,bytes.data(),1048576,&error)==NCMA_OK,"Actual registered stage compilation");bytes.resize(result.bytecode_bytes);return bytes;};
         const auto text=Rendering::ScenePipelineKernel::ShaderSource();
         auto gv=code(text,"VSMain",0),gp=code(text,"PSMain",1),sv=code(text,"VSShadowAlpha",0),sp=code(text,"PSShadow",1),tv=code(text,"VSTone",0),tp=code(text,"PSTone",1);
         auto pairFor=[](const std::vector<uint8_t>& v,const std::vector<uint8_t>& p){return NcmaShaderPairV1{32,1,static_cast<uint32_t>(v.size()),static_cast<uint32_t>(p.size()),v.data(),p.data()};};
         NcmaSceneShadersV1 stageGroup{104,1,pairFor(gv,gp),pairFor(sv,sp),pairFor(tv,tp)};NcmaScenePipelineDescriptionV4 description{16,256,256,256};NcmaGpuResourceV3 key{123,456};
         auto bad=stageGroup;bad.version=2;Check(stages.create_scene(renderModule,handle,&description,&bad,&key,&error)==NCMA_ABI_MISMATCH&&key.value==123&&renderer->backend->GetLiveResourceCount()==0,"Wrong group ABI unpublished");
         bad=stageGroup;bad.tone.pixel=tv.data();bad.tone.pixel_bytes=static_cast<uint32_t>(tv.size());Check(stages.create_scene(renderModule,handle,&description,&bad,&key,&error)==NCMA_INVALID_ARGUMENT&&key.value==123&&renderer->backend->GetLiveResourceCount()==0,"Last stage wrong before ANY GPU publication");
         std::string forged{text};for(size_t at=0;(at=forged.find("ShadowParameters",at))!=std::string::npos;at+=16)forged.replace(at,16,"ForgedLastMember");
         auto forgedPs=code(forged,"PSMain",1);bad=stageGroup;bad.geometry.pixel=forgedPs.data();bad.geometry.pixel_bytes=static_cast<uint32_t>(forgedPs.size());
         Check(stages.create_scene(renderModule,handle,&description,&bad,&key,&error)==NCMA_INVALID_ARGUMENT&&key.value==123,"Actual last geometry cbuffer member rejected");
         testTonePreparationThrow=true;Check(stages.create_scene(renderModule,handle,&description,&stageGroup,&key,&error)==NCMA_INTERNAL_ERROR&&key.value==123&&renderer->backend->GetLiveResourceCount()==0&&renderer->scenePipelines.empty(),"Group creation diagnostic exception releases ALL programs/resources");testTonePreparationThrow=false;
         Check(stages.create_scene(renderModule,handle,&description,&stageGroup,&key,&error)==NCMA_OK,"Actual full registered group creation");auto count=renderer->backend->GetLiveResourceCount();auto creates=renderer->sceneStats.creates;
         testTonePreparationThrow=true;Check(stages.replace_scene(renderModule,handle,key,&stageGroup,&error)==NCMA_INTERNAL_ERROR&&renderer->backend->GetLiveResourceCount()==count&&!renderer->failed,"Group diagnostic exception retains old whole group");testTonePreparationThrow=false;
         testWaitTimeout=true;Check(stages.replace_scene(renderModule,handle,key,&stageGroup,&error)==NCMA_SHUTDOWN_TIMEOUT&&renderer->backend->GetLiveResourceCount()==count,"Whole-group drain failure retains old and frees all candidates");testWaitTimeout=false;
         renderer->active=true;Check(stages.replace_scene(renderModule,handle,key,&stageGroup,&error)==NCMA_BUSY,"Group active frame rejection");renderer->active=false;
         Check(stages.replace_scene(renderModule,handle,key,&stageGroup,&error)==NCMA_OK&&renderer->sceneStats.creates==creates&&renderer->backend->GetLiveResourceCount()==count,"Whole-group replacement no target rebuild");
         Check(DestroyScenePipeline(renderModule,handle,key,&error)==NCMA_OK&&renderer->backend->GetLiveResourceCount()==0,"Registered whole group closes");
        }
        Check(latest.query_scene_render(renderModule,1,&scene,47,&error)==NCMA_BUFFER_TOO_SMALL && error.required_bytes==48,"Short scene service table");
        Check(latest.query_scene_render(renderModule,1,&scene,sizeof(scene),&error)==NCMA_OK && scene.version==1 && scene.capabilities==1,"Scene service negotiation");
        const float vertices[36]{-0.8f,-0.7f,.5f,0,0,1,0,0,1,0,0,1, .6f,-.7f,.5f,0,0,1,1,0,1,0,0,1, -.8f,.7f,.5f,0,0,1,0,1,1,0,0,1};
        uint32_t indices[3]{0,1,2};
        NcmaMeshDescriptionV1 meshDesc{48,1,3,3,144,12,48,0,reinterpret_cast<const uint8_t*>(vertices),indices};
        NcmaGpuMeshV1 mesh{123,456};
        auto badMesh=meshDesc;badMesh.vertex_count=UINT32_MAX;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT && mesh.value==123,"Count overflow rejected without publishing");
        badMesh=meshDesc;badMesh.layout=99;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Unknown mesh layout");
        badMesh=meshDesc;badMesh.vertex_bytes--;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Short vertex buffer");
        badMesh=meshDesc;badMesh.index_bytes--;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Short index buffer");
        badMesh=meshDesc;badMesh.struct_size=47;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Mesh descriptor version/size");
        badMesh=meshDesc;badMesh.reserved=1;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Mesh reserved bits");
        indices[2]=3;
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&mesh,&error)==NCMA_INVALID_ARGUMENT,"Index out of bounds");indices[2]=2;
        Check(renderer->backend->GetLiveResourceCount()==0 && renderer->meshes.empty(),"Failed mesh create leaked resources");
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&mesh,&error)==NCMA_OK,"Mesh create");
        uint32_t meshThread=0;
        std::thread meshWorker([&]{NcmaGpuMeshV1 result{};NcmaErrorV1 e{};meshThread=scene.create_mesh(renderModule,handle,&meshDesc,&result,&e);});meshWorker.join();
        Check(meshThread==NCMA_WRONG_THREAD,"Mesh create owner thread");
        auto foreignMesh=mesh;foreignMesh.generation++;
        Check(scene.destroy_mesh(renderModule,handle,foreignMesh,&error)==NCMA_INVALID_HANDLE,"Mesh generation ownership");
        NcmaMeshFrameV1 meshFrame{64,1,1,handle,{0,0,256,256},{0,0,0,1},{0,0}};
        NcmaMeshDrawV1 draw{mesh,0,3,{0,0},{},{1,1,1,1}};
        for(int i=0;i<16;++i)draw.model_view_projection[i]=i%5==0?1.0f:0.0f;
        draw.index_count=6;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_INVALID_ARGUMENT && renderer->stats.submitted_frames==0,"Full validation before GPU");draw.index_count=3;
        draw.reserved[1]=1;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_INVALID_ARGUMENT,"Reserved draw bits");draw.reserved[1]=0;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_OK,"Actual mesh submit");
        Check(scene.destroy_mesh(renderModule,handle,mesh,&error)==NCMA_BUSY,"Active mesh release retained");
        Check(api.present(renderModule,handle,&error)==NCMA_OK,"Mesh present");
        NcmaSceneRenderStatsV1 meshStats{};
        Check(scene.stats(renderModule,handle,&meshStats,&error)==NCMA_OK && meshStats.mesh_creates==1 && meshStats.uploaded_bytes==156 && meshStats.live_meshes==1,"Mesh counters");
        Check(scene.destroy_mesh(renderModule,handle,mesh,&error)==NCMA_OK,"Mesh release after completion");
        Check(scene.destroy_mesh(renderModule,handle,mesh,&error)==NCMA_INVALID_HANDLE,"Stale mesh");
        Check(renderer->backend->GetLiveResourceCount()==0,"Mesh kernel/geometry teardown");
        std::vector<NcmaGpuMeshV1> many(128);
        for(auto& resource:many)Check(scene.create_mesh(renderModule,handle,&meshDesc,&resource,&error)==NCMA_OK,"Mesh budget allocation");
        NcmaGpuMeshV1 refused{};
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&refused,&error)==NCMA_INVALID_ARGUMENT && refused.value==0,"128 mesh budget transactional refusal");
        for(auto resource:many)Check(scene.destroy_mesh(renderModule,handle,resource,&error)==NCMA_OK,"Mesh budget release");
        // Budget arithmetic at the resident limit, without allocating 256MiB in this fault test.
        renderer->meshStats.resident_bytes=256ull*1024*1024;
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&refused,&error)==NCMA_INVALID_ARGUMENT && renderer->meshes.empty(),"Resident byte budget preflight");
        renderer->meshStats.resident_bytes=0;
        Check(renderer->backend->GetLiveResourceCount()==0,"All mesh GPU objects released");
        NcmaSceneRenderApiV2 bind{};
        Check(latest.query_scene_render(renderModule,2,&bind,55,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==56,"Short bind service");
        Check(latest.query_scene_render(renderModule,2,&bind,sizeof(bind),&error)==NCMA_OK&&bind.base.version==2&&bind.base.capabilities==3&&bind.create_bind_pose_mesh,"Bind service negotiation");
        uint8_t skinVertices[240]{};float palette[16]{};for(int i=0;i<16;++i)palette[i]=i%5==0?1.0f:0.0f;
        for(int i=0;i<3;++i){std::memcpy(skinVertices+i*80,vertices+i*12,48);const float weight=1;std::memcpy(skinVertices+i*80+56,&weight,4);}
        NcmaBindPoseMeshDescriptionV2 skin{{64,2,3,3,240,12,80,0,skinVertices,indices},1,64,palette};
        auto badSkin=skin;badSkin.palette_bytes=63;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&badSkin,&refused,&error)==NCMA_INVALID_ARGUMENT&&refused.value==0,"Palette byte preflight");
        badSkin=skin;badSkin.palette_count=4097;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&badSkin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Palette count budget");
        badSkin=skin;badSkin.mesh.vertex_count=UINT32_MAX;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&badSkin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Skin count overflow");
        palette[15]=0;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Nonaffine palette");palette[15]=1;
        palette[0]=std::numeric_limits<float>::quiet_NaN();
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Nonfinite palette");palette[0]=1;
        skinVertices[48]=1;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Active palette joint bound");skinVertices[48]=0;
        const float invalidWeight=-1;std::memcpy(skinVertices+56,&invalidWeight,4);
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Negative weight");const float one=1;std::memcpy(skinVertices+56,&one,4);
        skinVertices[72]=1;
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_INVALID_ARGUMENT,"Nonzero skin padding");skinVertices[72]=0;
        badMesh=skin.mesh;badMesh.struct_size=48;
        Check(scene.create_mesh(renderModule,handle,&badMesh,&refused,&error)==NCMA_INVALID_ARGUMENT,"Static v1 cannot silently accept skin layout");
        Check(refused.value==0&&renderer->meshes.empty()&&renderer->backend->GetLiveResourceCount()==0,"Bind negatives published/leaked resources");
        Check(bind.create_bind_pose_mesh(renderModule,handle,&skin,&refused,&error)==NCMA_OK,"Bind mesh create");
        Check(renderer->meshes.at(refused.value)->vertexStride==80&&renderer->meshStats.resident_bytes==252,"Bind mesh resident stride/bytes");
        Check(scene.destroy_mesh(renderModule,handle,refused,&error)==NCMA_OK&&renderer->backend->GetLiveResourceCount()==0,"Bind mesh drain via v1 lease");
        NcmaResourceRenderApiV3 typed{};
        Check(latest.query_scene_render(renderModule,3,&typed,71,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==72,"Short resource service");
        Check(latest.query_scene_render(renderModule,3,&typed,sizeof(typed),&error)==NCMA_OK&&typed.version==3&&typed.capabilities==0x3c,"Resource service negotiation");
        uint8_t rgba[4]{128,64,32,255};NcmaTextureMipV3 mip{1,1,0,4};
        NcmaTextureDescriptionV3 textureDesc{48,1,1,2,1,4,{0,0},&mip,rgba};NcmaGpuResourceV3 texture{123,456},material{},target{};
        auto invalidTexture=textureDesc;invalidTexture.width=4097;
        Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT&&texture.value==123,"Texture dimension candidate unpublished");
        invalidTexture=textureDesc;invalidTexture.format=99;Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT,"Unknown texture format");
        mip.row_pitch=3;Check(typed.create_texture(renderModule,handle,&textureDesc,&texture,&error)==NCMA_INVALID_ARGUMENT,"Texture stride");mip.row_pitch=4;
        invalidTexture=textureDesc;invalidTexture.data_bytes=5;Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT,"Trailing texture bytes");
        invalidTexture=textureDesc;invalidTexture.width=2;Check(typed.create_texture(renderModule,handle,&invalidTexture,&texture,&error)==NCMA_INVALID_ARGUMENT,"Incomplete/overbudget mip");
        const auto resourceCount=renderer->backend->GetLiveResourceCount();
        Check(typed.create_texture(renderModule,handle,&textureDesc,&texture,&error)==NCMA_OK,"Texture initial upload");
        NcmaMaterialDescriptionV3 materialDesc{};materialDesc.struct_size=160;for(float& x:materialDesc.base_color)x=1;materialDesc.surface[1]=.5f;materialDesc.surface[2]=1;materialDesc.surface[3]=.5f;materialDesc.textures[0]=texture;
        materialDesc.textures[1]=texture;Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_INVALID_ARGUMENT&&material.value==0,"sRGB normal role rejected");materialDesc.textures[1]={};
        materialDesc.channels[0]=4;Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_INVALID_ARGUMENT,"Invalid material channel");materialDesc.channels[0]=0;
        materialDesc.textures[0].generation++;Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_INVALID_HANDLE,"Foreign texture generation");materialDesc.textures[0]=texture;
        Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_OK,"Lazy material shader create");
        Check(typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_BUSY,"Material pins texture");
        NcmaTargetDescriptionV3 targetDesc{16,256,256,0};auto badTarget=targetDesc;badTarget.width=UINT32_MAX;Check(typed.create_target(renderModule,handle,&badTarget,&target,&error)==NCMA_INVALID_ARGUMENT,"Target integer overflow preflight");
        Check(typed.create_target(renderModule,handle,&targetDesc,&target,&error)==NCMA_OK,"Target create");
        ID3D11ShaderResourceView* imageView=nullptr;
        Check(ncma_renderer_gui_image_v1(renderModule,handle,texture,0,0,&imageView,&error)==NCMA_INVALID_HANDLE,"GUI accepts target tokens only");
        auto foreignTarget=target;foreignTarget.generation++;
        Check(ncma_renderer_gui_image_v1(renderModule,handle,foreignTarget,0,0,&imageView,&error)==NCMA_INVALID_HANDLE,"GUI image foreign generation");
        Check(ncma_renderer_gui_image_v1(renderModule,handle,target,1,0,&imageView,&error)==NCMA_BUSY,"Unsubmitted target cannot masquerade as current image");
        for(int i=0;i<64;i++)Check(ncma_renderer_gui_image_v1(renderModule,handle,target,0,1,&imageView,&error)==NCMA_OK&&imageView,"Bounded GUI image pin");
        Check(ncma_renderer_gui_image_v1(renderModule,handle,target,0,1,&imageView,&error)==NCMA_BUSY,"GUI pin overflow");
        Check(typed.destroy_resource(renderModule,handle,target,&error)==NCMA_BUSY,"CPU GUI data pins target before GPU submit");
        for(int i=0;i<64;i++)Check(ncma_renderer_release_gui_image_v1(renderModule,handle,target,&error)==NCMA_OK,"GUI image unpin");
        Check(ncma_renderer_release_gui_image_v1(renderModule,handle,target,&error)==NCMA_INVALID_HANDLE,"GUI image double unpin");
        NcmaGpuMeshV1 typedMesh{};Check(scene.create_mesh(renderModule,handle,&meshDesc,&typedMesh,&error)==NCMA_OK,"Typed negative mesh");
        NcmaResourceDrawV3 resourceDraw{};resourceDraw.mesh=typedMesh;resourceDraw.material=material;resourceDraw.index_count=3;
        for(int i=0;i<16;++i)resourceDraw.model[i]=resourceDraw.model_view_projection[i]=resourceDraw.normal_matrix[i]=i%5==0?1.f:0.f;
        NcmaResourceFrameV3 resourceFrame{};resourceFrame.struct_size=136;resourceFrame.draw_count=1;resourceFrame.frame=2;resourceFrame.generation=handle;resourceFrame.target=target;resourceFrame.viewport[2]=resourceFrame.viewport[3]=256;resourceFrame.clear[3]=1;resourceFrame.camera[2]=2;resourceFrame.light_direction[2]=1;resourceFrame.exposure=1;resourceFrame.ambient=.03f;
        resourceDraw.model[15]=0;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_ARGUMENT,"Nonaffine typed draw");resourceDraw.model[15]=1;
        resourceDraw.normal_matrix[0]=2;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_ARGUMENT,"Inconsistent inverse-transpose");resourceDraw.normal_matrix[0]=1;
        resourceDraw.material=texture;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_HANDLE,"Wrong type resource draw");resourceDraw.material=material;
        resourceFrame.draw_count=4097;Check(typed.submit(renderModule,handle,&resourceFrame,&resourceDraw,&error)==NCMA_INVALID_ARGUMENT,"Typed batch budget");resourceFrame.draw_count=1;
        Check(renderer->lastFrame==1&&!renderer->active&&renderer->resourceStats.draws==0,"Rejected typed batch advanced frame");
        NcmaScenePipelineApiV4 pipelineApi{};
        Check(latest.query_scene_render(renderModule,4,&pipelineApi,47,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==48,"Short scene pipeline service");
        Check(latest.query_scene_render(renderModule,4,&pipelineApi,48,&error)==NCMA_OK&&pipelineApi.version==4&&pipelineApi.capabilities==7,"Scene pipeline negotiation");
        NcmaScenePipelineDescriptionV4 description{16,256,256,512};NcmaGpuResourceV3 pipelineKey{123,456};auto invalidDescription=description;invalidDescription.shadow_resolution=300;
        const auto pipelineResourceCount=renderer->backend->GetLiveResourceCount();
        Check(pipelineApi.create(renderModule,handle,&invalidDescription,&pipelineKey,&error)==NCMA_INVALID_ARGUMENT&&pipelineKey.value==123,"Invalid shadow candidate unpublished");
        invalidDescription=description;invalidDescription.width=UINT32_MAX;
        Check(pipelineApi.create(renderModule,handle,&invalidDescription,&pipelineKey,&error)==NCMA_INVALID_ARGUMENT,"Scene dimensions overflow");
        Check(pipelineApi.create(renderModule,handle,&description,&pipelineKey,&error)==NCMA_OK,"Actual scene shaders/resources create");
        NcmaSceneFrameV4 sf{};sf.base=resourceFrame;sf.base.struct_size=240;sf.base.camera[3]=1;sf.pipeline=pipelineKey;sf.pass_count=3;
        for(int i=0;i<16;++i)sf.light_view_projection[i]=i%5==0?1.f:0.f;sf.shadow[3]=3;
        NcmaSceneDrawV4 batch[2]{{resourceDraw,{0,.5f,0,0}},{resourceDraw,{0,.5f,0,0}}};
        NcmaScenePassV4 scenePasses[3]{{6,{}},{7,{.03f,0,0}},{8,{1,0,0}}};
        sf.base.draw_count=2;batch[1].draw.reserved[0]=1;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Last invalid scene draw preflight");batch[1].draw.reserved[0]=0;
        sf.caster_count=2;batch[1].override_surface[2]=2;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,batch,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Last invalid caster/scalar preflight");batch[1].override_surface[2]=0;
        sf.caster_count=0;sf.base.draw_count=4097;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene bounded geometry batch");sf.base.draw_count=2;
        sf.caster_count=4097;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,batch,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene bounded shadow batch");sf.caster_count=0;
        sf.pipeline.generation++;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene foreign pipeline generation");sf.pipeline=pipelineKey;
        sf.light_view_projection[0]=std::numeric_limits<float>::quiet_NaN();
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene nonfinite light matrix");sf.light_view_projection[0]=1;
        scenePasses[0].operation=8;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene tone before geometry rejected");scenePasses[0].operation=6;
        scenePasses[2].parameters[0]=0;
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_INVALID_ARGUMENT,"Scene invalid exposure");scenePasses[2].parameters[0]=1;
        NcmaScenePipelineStatsV4 ss{};
        Check(pipelineApi.stats(renderModule,handle,&ss,&error)==NCMA_OK&&ss.pipelines==1&&ss.geometry_draws==0&&ss.shadow_draws==0&&renderer->lastFrame==1&&!renderer->active,"Rejected scene has no partial execution");
        uint32_t sceneWrongThread=0;
        std::thread sceneWorker([&]{NcmaScenePipelineStatsV4 stats{};NcmaErrorV1 e{};sceneWrongThread=pipelineApi.stats(renderModule,handle,&stats,&e);});sceneWorker.join();
        Check(sceneWrongThread==NCMA_WRONG_THREAD,"Scene owner thread required");
        auto foreignPipeline=pipelineKey;foreignPipeline.generation++;
        Check(pipelineApi.destroy(renderModule,handle,foreignPipeline,&error)==NCMA_INVALID_HANDLE,"Foreign pipeline release");
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_OK,"Valid scene batch executes after all negative cases");
        Check(pipelineApi.destroy(renderModule,handle,pipelineKey,&error)==NCMA_BUSY,"Active scene group retained");
        Check(api.present(renderModule,handle,&error)==NCMA_OK,"Actual scene present");
        Check(pipelineApi.destroy(renderModule,handle,pipelineKey,&error)==NCMA_OK&&renderer->backend->GetLiveResourceCount()==pipelineResourceCount,"Scene group fully drained");
        Check(pipelineApi.destroy(renderModule,handle,pipelineKey,&error)==NCMA_INVALID_HANDLE,"Released scene pipeline");
        Check(scene.destroy_mesh(renderModule,handle,typedMesh,&error)==NCMA_OK,"Typed negative mesh drain");
        Check(typed.capture_target(renderModule,handle,target,nullptr,0,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==256*256*4,"Target readback short capacity");
        renderer->resourceStats.resident_bytes=256ull*1024*1024;
        NcmaGpuResourceV3 denied{};Check(typed.create_texture(renderModule,handle,&textureDesc,&denied,&error)==NCMA_INVALID_ARGUMENT&&denied.value==0,"Resident texture budget");renderer->resourceStats.resident_bytes=4+256*256*8;
        Check(typed.destroy_resource(renderModule,handle,target,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,material,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_OK,"Typed dependency drain");
        Check(typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_INVALID_HANDLE,"Released resource");
        Check(renderer->resourceStats.resident_bytes==0&&renderer->backend->GetLiveResourceCount()==resourceCount,"Resource candidate/fallback GPU leak");
        NcmaSkinApiV5 skinApi{};
        Check(latest.query_scene_render(renderModule,5,&skinApi,55,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==56,"Short skin API");
        Check(latest.query_scene_render(renderModule,5,&skinApi,56,&error)==NCMA_OK&&skinApi.version==5&&skinApi.capabilities==3,"Skin API negotiation");
        std::array<uint8_t,240> gpuSkinVertices{};
        for(int i=0;i<3;i++){std::memcpy(gpuSkinVertices.data()+i*80,vertices+i*12,48);float weight=1;std::memcpy(gpuSkinVertices.data()+i*80+64,&weight,4);}
        NcmaSkinMeshV5 skinDesc{{56,3,3,3,240,12,80,0,gpuSkinVertices.data(),indices},1,0};NcmaGpuMeshV1 skinMesh{123,456};
        auto badGpuSkin=skinDesc;badGpuSkin.binding_count=0;Check(skinApi.create(renderModule,handle,&badGpuSkin,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Skin create candidate rejected");
        badGpuSkin.binding_count=1025;Check(skinApi.create(renderModule,handle,&badGpuSkin,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Skin binding budget rejected");
        float zeroWeight=0;std::memcpy(gpuSkinVertices.data()+64,&zeroWeight,4);
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Zero influence sum rejected");
        float negativeWeight=-1;std::memcpy(gpuSkinVertices.data()+64,&negativeWeight,4);
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Negative influence rejected");
        float validWeight=1;std::memcpy(gpuSkinVertices.data()+64,&validWeight,4);uint32_t badJoint=1;std::memcpy(gpuSkinVertices.data()+48,&badJoint,4);
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_INVALID_ARGUMENT&&skinMesh.value==123,"Mesh-local joint range rejected");
        badJoint=0;std::memcpy(gpuSkinVertices.data()+48,&badJoint,4);
        {NcmaShaderStagesApiV1 stages{};Check(latest.query_scene_render(renderModule,10,&stages,56,&error)==NCMA_OK,"Skin registered stages negotiation");
         auto skinCode=[&](std::string_view source){NcmaShaderCompileV1 request=originalRequest;request.source=reinterpret_cast<const uint8_t*>(source.data());request.source_bytes=static_cast<uint32_t>(source.size());request.entry="CSMain";request.entry_bytes=6;request.stage=2;
          NcmaShaderOutputV1 result{};std::array<NcmaShaderRowV1,256> rows{};std::vector<uint8_t> bytes(1048576);Check(shaders.compile(renderModule,handle,&request,&result,rows.data(),256,bytes.data(),1048576,&error)==NCMA_OK,"Actual skin registered compile");bytes.resize(result.bytecode_bytes);return bytes;};
         auto text=Rendering::SkinKernel::ShaderSource();auto bytes=skinCode(text);NcmaComputeShaderV1 program{24,1,static_cast<uint32_t>(bytes.size()),0,bytes.data()};NcmaGpuMeshV1 key{123,456};
         auto bad=program;bad.reserved=1;Check(stages.create_skin(renderModule,handle,&skinDesc,&bad,&key,&error)==NCMA_INVALID_ARGUMENT&&key.value==123,"Skin reserved before publication");
         std::string wrongThreads{text};auto at=wrongThreads.find("numthreads(64,1,1)");Check(at!=std::string::npos,"Skin group fixture");wrongThreads.replace(at,18,"numthreads(32,1,1)");auto threadBytes=skinCode(wrongThreads);bad=program;bad.bytecode=threadBytes.data();bad.bytes=static_cast<uint32_t>(threadBytes.size());
         Check(stages.create_skin(renderModule,handle,&skinDesc,&bad,&key,&error)==NCMA_INVALID_ARGUMENT&&key.value==123&&!renderer->skinKernel,"Actual wrong threadgroup rejected before GPU");
         std::string wrongLayout{text};at=wrongLayout.find("float3 p;float3 n;");Check(at!=std::string::npos,"Skin layout fixture");wrongLayout.replace(at,18,"float3 n;float3 p;");auto layoutBytes=skinCode(wrongLayout);bad=program;bad.bytecode=layoutBytes.data();bad.bytes=static_cast<uint32_t>(layoutBytes.size());
         Check(stages.create_skin(renderModule,handle,&skinDesc,&bad,&key,&error)==NCMA_INVALID_ARGUMENT&&key.value==123&&!renderer->skinKernel,"Same-stride wrong actual nested member offsets rejected");
         testTonePreparationThrow=true;Check(stages.create_skin(renderModule,handle,&skinDesc,&program,&key,&error)==NCMA_INTERNAL_ERROR&&key.value==123&&!renderer->skinKernel&&renderer->backend->GetLiveResourceCount()==resourceCount,"Registered skin diagnostic creation atomic");testTonePreparationThrow=false;
         Check(stages.create_skin(renderModule,handle,&skinDesc,&program,&key,&error)==NCMA_OK&&renderer->skinKernel->Matches(program),"Registered actual compute first kernel creation");auto count=renderer->backend->GetLiveResourceCount();auto creates=renderer->skinStats.creates;
         testTonePreparationThrow=true;Check(stages.replace_skin(renderModule,handle,&program,&error)==NCMA_INTERNAL_ERROR&&renderer->skinKernel->Matches(program)&&renderer->backend->GetLiveResourceCount()==count&&!renderer->failed,"Compute diagnostic exception preserves program/resources");testTonePreparationThrow=false;
         testWaitTimeout=true;Check(stages.replace_skin(renderModule,handle,&program,&error)==NCMA_SHUTDOWN_TIMEOUT&&renderer->skinKernel->Matches(program),"Compute drain failure retains exact program");testWaitTimeout=false;
         Check(stages.replace_skin(renderModule,handle,&program,&error)==NCMA_OK&&renderer->skinStats.creates==creates&&renderer->backend->GetLiveResourceCount()==count,"Registered compute replaces no mesh/palette resources");
         Check(skinApi.destroy(renderModule,handle,key,&error)==NCMA_OK&&!renderer->skinKernel&&renderer->backend->GetLiveResourceCount()==resourceCount,"Last registered skin resource closes");
        }
        Check(skinApi.create(renderModule,handle,&skinDesc,&skinMesh,&error)==NCMA_OK,"Actual compute skin source/output create");
        NcmaMeshDescriptionV1 mixedStaticDesc{48,1,3,3,144,12,48,0,reinterpret_cast<const uint8_t*>(vertices),indices};NcmaGpuMeshV1 mixedStatic{};
        Check(scene.create_mesh(renderModule,handle,&mixedStaticDesc,&mixedStatic,&error)==NCMA_OK,"Mixed static/skin source");
        Check(scene.destroy_mesh(renderModule,handle,mixedStatic,&error)==NCMA_OK,"Static released before last skin");
        NcmaSkinPaletteV5 gpuPalette{};for(int i=0;i<16;i++)gpuPalette.model[i]=gpuPalette.normal[i]=i%5==0?1.f:0.f;gpuPalette.model[12]=.25f;
        NcmaSkinRequestV5 skinJobs[2]{{skinMesh,0,1},{skinMesh,1,1}};NcmaSkinPaletteV5 pair[2]{gpuPalette,gpuPalette};NcmaSkinBatchV5 skinBatch{32,2,3,handle,2,0};NcmaSkinStatsV5 skinStatus{};
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,pair,&error)==NCMA_INVALID_ARGUMENT,"Duplicate GPU skin output preflight");
        skinBatch.request_count=1;skinBatch.palette_count=1;gpuPalette.normal[0]=2;
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_INVALID_ARGUMENT,"Skin normal inverse-transpose preflight");gpuPalette.normal[0]=1;
        auto foreignSkin=skinMesh;foreignSkin.generation++;skinJobs[0].mesh=foreignSkin;
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_INVALID_HANDLE,"Foreign skin renderer generation");skinJobs[0].mesh=skinMesh;
        Check(skinApi.stats(renderModule,handle,&skinStatus,&error)==NCMA_OK&&skinStatus.batches==0&&renderer->skins.at(skinMesh.value)->frame==0,"Rejected skin did not dispatch/publish");
        uint32_t skinWrongThread=0;std::thread skinThread([&]{NcmaSkinStatsV5 s{};NcmaErrorV1 e{};skinWrongThread=skinApi.stats(renderModule,handle,&s,&e);});skinThread.join();Check(skinWrongThread==NCMA_WRONG_THREAD,"Skin owner thread");
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_OK,"GPU skin dispatch");
        std::array<float,36> skinResult{};Check(skinApi.capture(renderModule,handle,skinMesh,reinterpret_cast<uint8_t*>(skinResult.data()),144,&error)==NCMA_OK,"GPU skin numerical readback");
        for(int i=0;i<3;i++){Check(std::abs(skinResult[static_cast<size_t>(i)*12]-vertices[i*12]-.25f)<1e-5f,"GPU skin position oracle");Check(std::abs(skinResult[static_cast<size_t>(i)*12+5]-1)<1e-5f,"GPU skin normal oracle");}
        Check(skinApi.update(renderModule,handle,&skinBatch,skinJobs,&gpuPalette,&error)==NCMA_INVALID_ARGUMENT,"Repeated pose frame rejected");
        Check(scene.destroy_mesh(renderModule,handle,skinMesh,&error)==NCMA_INVALID_ARGUMENT,"Skin is not an old static release type");
        Check(skinApi.destroy(renderModule,handle,skinMesh,&error)==NCMA_OK&&skinApi.stats(renderModule,handle,&skinStatus,&error)==NCMA_OK&&skinStatus.meshes==0&&skinStatus.resident_bytes==0,"Skin ring/source/output fully drained");
        Check(skinApi.destroy(renderModule,handle,skinMesh,&error)==NCMA_INVALID_HANDLE,"Released GPU skin handle");
        Check(renderer->backend->GetLiveResourceCount()==resourceCount,"Skin RHI resources leaked");
        uint32_t foreign=0;
        std::thread thread([&]{NcmaRendererStatsV1 status{};NcmaErrorV1 threadError{};foreign=api.stats(renderModule,handle,&status,&threadError);});thread.join();
        Check(foreign==NCMA_WRONG_THREAD,"Wrong thread rejected");
        Rhi::GraphicsPipelineDescription shader{};
        shader.VertexShaderSource="syntax_error";shader.PixelShaderSource="syntax_error";
        shader.VertexLayout.push_back({"POSITION",0,Rhi::VertexFormat::Float3,0});
        std::string diagnostic;
        Check(!renderer->backend->CreateGraphicsPipeline(shader,diagnostic),"Invalid shader unexpectedly compiled.");
        Check(!diagnostic.empty(),"Shader compilation diagnostic missing.");
        // Remove intentionally generated compile diagnostic from validation before successful draw.
        renderer->validation->ClearStoredMessages();
        Check(api.create_resources(renderModule,handle,&group,&error)==0,"Reference resource create");
        NcmaRenderFrameV1 frame{sizeof(frame),3,3,{},{0,0,256,256},1,.35F,.28F,0};
        for(int i=0;i<16;++i)frame.model[i]=i%5==0?1.0F:0.0F;
        NcmaRenderPassV1 passes[3]{{1,1,group,{}},{2,1,group,{}},{3,2,group,{}}};
        auto invalid=frame;invalid.pass_count=65;
        Check(api.submit(renderModule,handle,&invalid,passes,&error)==NCMA_INVALID_ARGUMENT,"Pass budget");
        passes[0].resources=handle;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_INVALID_HANDLE,"Wrong type handle");
        passes[0].resources=group;passes[2].shader_contract=1;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_INVALID_ARGUMENT,"Shader contract");
        passes[2].shader_contract=2;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==0,"Submit");
        Check(api.destroy_resources(renderModule,handle,group,&error)==NCMA_BUSY,"Active frame retained");
        Check(api.present(renderModule,handle,&error)==0,"Present");
        Check(api.wait_idle(renderModule,handle,&error)==0,"Wait GPU");
        NcmaGpuMeshV1 faultMesh{};
        Check(typed.create_texture(renderModule,handle,&textureDesc,&texture,&error)==NCMA_OK,"Fault texture create");materialDesc.textures[0]=texture;
        Check(typed.create_material(renderModule,handle,&materialDesc,&material,&error)==NCMA_OK&&typed.create_target(renderModule,handle,&targetDesc,&target,&error)==NCMA_OK,"Fault material/target create");
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&faultMesh,&error)==NCMA_OK,"Active fault mesh create");
        draw.mesh=faultMesh;meshFrame.frame=4;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_OK,"Active fault mesh submit");
        Check(Failure(&error,"Injected post-submit capture failure.")==NCMA_INTERNAL_ERROR,"Capture execution fault fail-stop");
        Check(!renderer->active && !renderer->measuring,"Faulted active frame/query did not abort");
        Check(api.present(renderModule,handle,&error)==NCMA_INTERNAL_ERROR,"Faulted frame cannot present");
        Check(scene.destroy_mesh(renderModule,handle,faultMesh,&error)==NCMA_OK && renderer->meshes.empty(),"Faulted active mesh can drain");
        Check(typed.create_texture(renderModule,handle,&textureDesc,&denied,&error)==NCMA_INTERNAL_ERROR,"Fault texture creation blocked");
        Check(typed.destroy_resource(renderModule,handle,target,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,material,&error)==NCMA_OK&&typed.destroy_resource(renderModule,handle,texture,&error)==NCMA_OK,"Faulted typed resources drain");
        try {ExecutionScope scope;throw std::runtime_error("Injected post-validation execution failure.");}catch(const std::runtime_error&){}
        frame.frame=5;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_INTERNAL_ERROR,"Execution exception fail-stop");
        renderer->failed=true;renderer->faultResult=NCMA_DEVICE_LOST;renderer->stats.state=2; // Device-lost state machine injection, not a driver reset.
        frame.frame=5;
        Check(api.submit(renderModule,handle,&frame,passes,&error)==NCMA_DEVICE_LOST,"Lost submit fail-stop");
        Check(api.present(renderModule,handle,&error)==NCMA_DEVICE_LOST,"Lost present fail-stop");
        Check(api.resize(renderModule,handle,300,300,&error)==NCMA_DEVICE_LOST,"Lost resize fail-stop");
        meshFrame.frame=5;
        Check(scene.submit_meshes(renderModule,handle,&meshFrame,&draw,&error)==NCMA_DEVICE_LOST,"Lost static batch fail-stop");
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&refused,&error)==NCMA_DEVICE_LOST,"Lost mesh create fail-stop");
        Check(pipelineApi.create(renderModule,handle,&description,&pipelineKey,&error)==NCMA_DEVICE_LOST,"Lost scene create fail-stop");
        Check(pipelineApi.submit(renderModule,handle,&sf,batch,nullptr,scenePasses,&error)==NCMA_DEVICE_LOST,"Lost scene submit fail-stop");
        Check(api.destroy_resources(renderModule,handle,group,&error)==0,"Faulted release");
        Check(api.destroy_resources(renderModule,handle,group,&error)==NCMA_INVALID_HANDLE,"Stale group");
        Check(renderer->backend->GetLiveResourceCount()==0,"Native GPU resource maps leaked.");
        Check(api.destroy_renderer(renderModule,handle,&error)==0,"Destroy");
        Check(api.stats(renderModule,handle,nullptr,&error)==NCMA_INVALID_HANDLE,"Stale renderer");
        NcmaUiApiV1 ui{};
        Check(latest.query_scene_render(renderModule,6,&ui,sizeof(ui)-1,&error)==NCMA_BUFFER_TOO_SMALL&&error.required_bytes==sizeof(ui),"Short UI table");
        Check(latest.query_scene_render(renderModule,6,&ui,sizeof(ui),&error)==NCMA_OK&&ui.version==1&&ui.capabilities==7,"UI table negotiate");
        Check(ui.create_ui_renderer(renderModule,&desc,&handle,&error)==NCMA_OK,"UI-only renderer create");
        Check(api.create_resources(renderModule,handle,&group,&error)==NCMA_UNSUPPORTED_FEATURE,"UI-only cannot create 3D reference resources");
        Check(scene.create_mesh(renderModule,handle,&meshDesc,&refused,&error)==NCMA_UNSUPPORTED_FEATURE,"UI-only cannot create scene mesh");
        uint8_t whitePixels[4]{255,255,255,255};NcmaUiImageV1 imageInput{sizeof(imageInput),1,1,4,whitePixels};NcmaUiKeyV1 imageKey{},listKey{};
        auto badImage=imageInput;badImage.byte_count=3;
        Check(ui.create_image(renderModule,handle,&badImage,&imageKey,&error)==NCMA_INVALID_ARGUMENT&&!renderer->ui,"Invalid UI image does not initialize GPU UI state");
        Check(ui.create_image(renderModule,handle,&imageInput,&imageKey,&error)==NCMA_OK,"UI image create");
        NcmaUiVertexV1 uiVertices[3]{{{0,0},{0,0},{1,0,0,1},{0,0},{100,100},0},{{100,0},{1,0},{1,0,0,1},{100,0},{100,100},0},{{0,100},{0,1},{1,0,0,1},{0,100},{100,100},0}};
        NcmaUiBatchV1 uiBatch{0,3,imageKey,{0,0,256,256}};NcmaUiListV1 listInput{sizeof(listInput),3,1,0,uiVertices,&uiBatch};
        uiBatch.image.generation--;
        Check(ui.create_list(renderModule,handle,&listInput,&listKey,&error)==NCMA_INVALID_ARGUMENT,"Foreign UI image generation");uiBatch.image=imageKey;
        uiVertices[0].color[0]=std::numeric_limits<float>::quiet_NaN();
        Check(ui.create_list(renderModule,handle,&listInput,&listKey,&error)==NCMA_INVALID_ARGUMENT,"Nonfinite UI vertex before execution");uiVertices[0].color[0]=1;
        Check(ui.create_list(renderModule,handle,&listInput,&listKey,&error)==NCMA_OK,"UI display list create");
        Check(ui.destroy(renderModule,handle,imageKey,&error)==NCMA_BUSY,"UI list pins its images");
        NcmaUiTargetDescriptionV1 targetDescription{sizeof(targetDescription),128,128,0};NcmaUiKeyV1 uiTarget{},uiLease{};
        Check(uiTargets.create_target(renderModule,handle,&targetDescription,&uiTarget,&error)==NCMA_OK,"Color-only UI target create");
        NcmaUiTargetFrameV1 targetFrame{sizeof(targetFrame),0,1,1,uiTarget,listKey,{0,0,0,1}};
        Check(uiTargets.submit(renderModule,handle,&targetFrame,&error)==NCMA_OK&&!renderer->active&&!renderer->lastFrame&&renderer->stats.presents==0,"Offscreen production never presents/activates main frame");
        Check(uiTargets.acquire(renderModule,handle,uiTarget,1,1,&uiLease,&error)==NCMA_OK,"UI presentation acquire");
        ID3D11ShaderResourceView* borrowed=nullptr;
        Check(ncma_renderer_gui_cached_image_v1(renderModule,handle,{uiLease.value,uiLease.generation},2,0,&borrowed,&error)==NCMA_BUSY,"Lease exact presentation frame");
        Check(ncma_renderer_gui_cached_image_v1(renderModule,handle,{uiLease.value,uiLease.generation},1,1,&borrowed,&error)==NCMA_OK&&borrowed,"GUI pins exact UI lease");
        Check(uiTargets.release(renderModule,handle,uiLease,&error)==NCMA_BUSY&&uiTargets.destroy_target(renderModule,handle,uiTarget,&error)==NCMA_BUSY,"Pinned lease retains complete ownership");
        Check(ncma_renderer_release_gui_cached_image_v1(renderModule,handle,{uiLease.value,uiLease.generation},&error)==NCMA_OK,"GUI releases pin");
        Check(uiTargets.release(renderModule,handle,uiLease,&error)==NCMA_OK,"UI lease release");
        testWaitTimeout=true;Check(uiTargets.destroy_target(renderModule,handle,uiTarget,&error)==NCMA_SHUTDOWN_TIMEOUT&&renderer->uiTargets.size()==1&&renderer->uiTargetBytes==128*128*4,"Target timeout retains texture and owner");testWaitTimeout=false;
        Check(api.destroy_renderer(renderModule,handle,&error)==NCMA_BUSY,"Renderer refuses unload under UI resources");
        NcmaUiFrameV1 uiFrame{sizeof(uiFrame),0,1,listKey,{0,0,0,1}};
        Check(ui.submit(renderModule,handle,&uiFrame,&error)==NCMA_OK,"UI submit");
        uiFrame.overlay=1;Check(ui.submit(renderModule,handle,&uiFrame,&error)==NCMA_BUSY,"Repeated UI frame rejected");
        Check(Failure(&error,"Injected UI post-submit failure")==NCMA_INTERNAL_ERROR,"UI fault stops active frame");
        Check(uiTargets.acquire(renderModule,handle,uiTarget,1,2,&uiLease,&error)==NCMA_INTERNAL_ERROR,"Faulted target cannot acquire presentation");
        NcmaUiKeyV1 rejectedTarget{};Check(uiTargets.create_target(renderModule,handle,&targetDescription,&rejectedTarget,&error)==NCMA_INTERNAL_ERROR&&!rejectedTarget.value&&renderer->uiTargets.size()==1,"Faulted target cannot allocate more GPU resources");
        targetFrame.frame=2;targetFrame.content_revision=2;Check(uiTargets.submit(renderModule,handle,&targetFrame,&error)==NCMA_INTERNAL_ERROR,"Faulted target cannot produce");
        Check(uiTargets.destroy_target(renderModule,handle,uiTarget,&error)==NCMA_OK&&renderer->uiTargets.empty(),"Explicit target close retry drains after fail-stop");
        uiFrame.frame=2;uiFrame.overlay=0;Check(ui.submit(renderModule,handle,&uiFrame,&error)==NCMA_INTERNAL_ERROR,"UI cannot submit after fault");
        Check(ui.destroy(renderModule,handle,listKey,&error)==NCMA_OK&&ui.destroy(renderModule,handle,imageKey,&error)==NCMA_OK,"Faulted UI resources drain");
        Check(api.destroy_renderer(renderModule,handle,&error)==NCMA_OK,"Faulted UI renderer closes");
        Check(api.module.shutdown(renderModule,&error)==0,"Renderer shutdown");
        Check(platform.destroy_window(platformModule,window,&error)==0,"Window destroy");
        Check(platform.module.shutdown(platformModule,&error)==0,"Platform shutdown");
        FreeLibrary(library);
        std::cout<<"Native render ABI bounds/thread/shader rejection and injected fault state passed; no real device reset performed.\n";return 0;
    }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}
}
